### ISSUE TITLE
Datagen fails on videos with different dimensions

### ISSUE THREAD

**Issue by ntabris** [murthylab/sleap#209]
We gather annotated frame images from all videos and then try to combine them into single ndarray here:

https://github.com/murthylab/sleap/blob/develop/sleap/nn/datagen.py#L137

If videos have different dimensions, this results in `ValueError('all input arrays must have the same shape')`.

Sample file at:
`/tigress/MMURTHY/Sama/X079_sleap/abdus-saboor/grant/nat.json`

**Comment by talmo** [comment]
Fixed in #440 (finally)
