### ISSUE TITLE
Cost threshold for track matching

### ISSUE THREAD

**Issue by ntabris** [murthylab/sleap#259]
For tracking, expose a cost threshold parameter such that any cost over this threshold is not considered a match—e.g., a centroid distance or iou threshold.

**Comment by talmo** [comment]
We have an IOU threshold in the tracker now.

**Comment by ntabris** [comment]
We have an IoU threshold for culling instances. This would be a *cost* threshold so that matches over a certain cost wouldn't be used. The Kalman filter code does this but the other tracking code does not.
