### ISSUE TITLE
GUI for reviewing eval metrics

### ISSUE THREAD

**Issue by ntabris** [murthylab/sleap#291]
(details need to be worked out)

**Comment by ntabris** [comment]
Mock up of table listing model for evaluation:

<img width="1294" alt="Whiteboard 1 -01" src="https://user-images.githubusercontent.com/46289310/80121411-45092700-855a-11ea-9ab0-60e8f1f23c5f.png">

**Comment by ntabris** [comment]
sortable table for comparing models:
- metrics: oks map, visibility prec, 95% dist
- each row shows different model
- ability to re-run inference
- labels from model, show timestamp and # of labels
- button to inspect individual model in more detail

(notes from discussion on 3/31)

**Comment by ntabris** [comment]
Basic version of dialog:

![image](https://user-images.githubusercontent.com/46289310/87350056-53495c80-c525-11ea-977f-7cfe9becc95f.png)

Doesn't yet have a way to re-run inference or get full metrics.

**Comment by ntabris** [comment]
There's now an "Evaluate Metrics for Trained Models..." command in the Predict menu which shows the table. Double-click on a row (model) to see full metrics, or use buttons under table:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/46289310/87484866-51ef6100-c605-11ea-9b21-e9b1f6fa0150.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/46289310/87484876-574cab80-c605-11ea-8de5-bfd5a92a6d46.png">

There's no way to (re-)run inference... we can add another issue if we want to add this enhancement.

**Comment by safas25** [comment]
> Basic version of dialog:
> 
> ![image](https://user-images.githubusercontent.com/46289310/87350056-53495c80-c525-11ea-977f-7cfe9becc95f.png)
> 
> Doesn't yet have a way to re-run inference or get full metrics.

Hi, nothing appears for me when I try this option. It's a blank table. Please help?
