### ISSUE TITLE
UI for catching user mistakes in labeling

### ISSUE THREAD

**Issue by ntabris** [murthylab/sleap#300]
There are various "mistakes" that are easy for a user to make when labeling but which cause problems or poor results when training. It may not even be obvious to the user that these are mistakes.

Some examples:

- labeling some but not all instances in a frame
- adding an instance w/ all the points marked as "not visible"

Issue #273 was another example.

We should add UI features to help the user catch such mistakes and possible mistakes (or confirm that something was intentional).

**Comment by talmo** [comment]
Mostly addressed in suggestions table for now.
