### ISSUE TITLE
Ubuntu 18.04 Trouble starting sleap 

### ISSUE THREAD

**Issue by ohchungha** [murthylab/sleap#340]
Hello! 

I have been experiencing trouble getting sleap to run. I am working with a fresh install of Ubuntu 18.04, and I am running CUDA 10.2 with NVIDIA driver 440.82. 

Per the Linux install instructions from sleap.ai, sleap was installed in a conda environment. 

First of all, tensorboard needed to be downgraded from 2.1.0 to 2.0.0, which was straightforward. 

Then, I got the below import error that I cannot figure out:

ImportError: /path/to/anaconda3/envs/sleap_env/lib/python3.6/site-packages/shiboken2/shiboken2.abi3.so: undefined symbol: _ZNSs4_Rep20_S_empty_rep_storageE, version GLIBCXX_3.4

Some googling suggested that this has something to do with pyside2 and shiboken2 and compiling, but the actual issue is opaque to me. 

any help would be appreciated!

Best,

Chung-ha

**Comment by ntabris** [comment]
Hi @ohchungha, thanks for bringing this to our attention! We're still in the pre-release stage and haven't built a new conda package for Linux (or MacOS) recently. I've run into PySide2/Shiboken issues in the past and I'm hoping these are resolved when installing a more recent version of SLEAP.

The best way right now to get SLEAP running on Linux is to create a Python 3.6 environment and then use `pip` to install SLEAP.

You can create an environment using anaconda like this:
```
conda create -n sleap_env python=3.6 -y
conda activate sleap_env
```

Assuming you already have the necessary GPU drivers (which it sounds like you do) you should be fine, but there's more info at https://www.tensorflow.org/install/gpu if needed.

You can then install SLEAP from the test PyPI server by running:
```
pip install --extra-index-url https://test.pypi.org/simple/ sleap==0.2.1
```

Let me know if this works!

**Comment by ohchungha** [comment]
Hello! Sorry it took me a little while to respond, but I did want to let you know sleap is loaded and it works very nicely on my data! thank you so much!

**Comment by ntabris** [comment]
Excellent, thanks for letting us know! If you don't mind, we'd love to hear about your data and how you're using SLEAP (sleap@princeton.edu).
