### ISSUE TITLE
Expose early stopping configuration in the GUI

### ISSUE THREAD

**Issue by talmo** [murthylab/sleap#349]
Expose all the fields in `TrainingJobConfig.optimization.early_stopping` in the training editor GUI (collapsible?)

**Comment by ntabris** [comment]
Added early stopping fields and re-arranged the columns so that the window still fits on my laptop screen:

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/46289310/81924952-d0039d00-95ad-11ea-86df-f36d1cf04148.png">

**Comment by ntabris** [comment]
Currently releasing v1.0.2 which includes these commits.
