### ISSUE TITLE
Include number of frames that failed in dialog after inference

### ISSUE THREAD

**Issue by talmo** [murthylab/sleap#352]
Communicates that instances couldn't be found in some number of frames, not that it was a bug that missed the frames.

This is useful since finding 0 instances in a frame is "new" behavior with the grouping methods.

**Comment by ntabris** [comment]
Does "failed" mean we got an error from inference on the frame? Or that we ran inference on the frame and didn't get any instances (so this is just the difference between number of frames we ran inference on and the number of frames we found instances on)? Or something else...? (I don't know what you mean about finding 0 instances being "new" behavior.)

**Comment by talmo** [comment]
Just the difference between number of frames we ran inference on and the number of frames we found instances on.

It's new behavior since the inference revamp.
