### ISSUE TITLE
Skeleton editor as a tree

### ISSUE THREAD

**Issue by talmo** [murthylab/sleap#354]
Implement skeleton editor panel using a [`QTreeView`](https://doc.qt.io/qtforpython/PySide2/QtWidgets/QTreeView.html) instead of two tables.

PAF skeletons need to be an [arborescence](https://networkx.github.io/documentation/stable/reference/algorithms/tree.html) (i.e., the skeleton graph needs to pass [`nx.algorithms.tree.recognition.is_arborescence`](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.recognition.is_arborescence.html#networkx.algorithms.tree.recognition.is_arborescence)), and this would explicitly solve the problem of users being able to construct invalid skeletons.

This should be a two column tree where the items are `Node`s like in the current GUI, but edges are inferred from the tree organization.

- Items (nodes) should be drag-and-droppable to assign them as children to different parent nodes. Multi-item select should not be possible. Drag and dropping a node onto a parent assigns it as a child, like in a file system browser.
- Second column should be dropdown to select mirror symmetric node for flip augmentation (for #228).
- Item labels should be editable to rename nodes.
- Flat trees (no children) should not be possible. Add node button behavior:
  - If no nodes in the skeleton, new node becomes root.
  - If any nodes in the skeleton, add them as children of the root after all other top-level children.
- Remove node button behavior:
  - If no children, just delete.
  - If has children and not a root node, all children get promoted to the deleted node's parent.
  - If has children and is a root node, first child gets promoted to root and then all children remain the same. (This logic might get tricky, so maybe just don't allow root node to be deleted, just grey out the remove button when root is selected.)

**Comment by ntabris** [comment]
I'm not a big fan of this design. I think it's going to be unintuitive for many users and tricky to handle all the possible edge cases.

Here are (non-functional) mockups:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/46289310/88934212-930a8680-d23d-11ea-889e-eb0cdbe45ff0.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/46289310/88934282-b0d7eb80-d23d-11ea-8e4c-a149cf82476a.png">

**My alternate proposal**

1. Quick, minimal way of addressing issue is to add a message (to training dialog? skeleton editor?) telling user that tree isn't valid for bottom-up training, maybe highlighting nodes/edges that are a problem.

2. Add a visual editor which would show the "average" instance (after user labels some instances—maybe another node layout before user labels instances, or maybe just require labeling before editing edges?) and lets user select (i) linear connections (node 0 -> 1 -> 2 -> ...), (ii) min spanning tree (let user pick initial node and use Prim's algo?), (iii) drag node to node (child to parent?) to edit edges.

Perhaps we could just default to using linear connections until user goes into skeleton editor? I think this editor would make it easier for users to see the structure of the skeleton graph and also to edit the graph if they want to try different edges for training bottom-up models.

**Comment by talmo** [comment]
We now have some basic skeleton validation before running training so I think I'll close this out until we have a better idea for a skeleton editor GUI.
