### ISSUE TITLE
creating labeled video on Colab

### ISSUE THREAD

**Issue by filos93** [murthylab/sleap#355]
Hey,

I'm trying to use SLEAP on your Colab notebook with my data, I have done training and inference, but I do not know how to create a labeled video. I can get the prediction file (ie, video filename.predictions.slp) and everything works fine, but I would like to generate the labeled video based on those predictions. Is this possible on Colab? 

Thanks a lot.

**Comment by ntabris** [comment]
Hi. There is a command line interface you can use to create the labeled videos (like the one at https://github.com/murthylab/sleap-datasets). Run:

`python -m sleap.io.visuals path/to/predictions.slp`

(In Colab, you should be able to use `!python -m sleap.io.visuals path/to/predictions.slp`).

There are also command line args to specify the frame rate, video scale, and range of frames if you don't want the entire video (`python -m sleap.io.visuals --help` for details).

Just so you know, it's very easy to install sleap on your local machine with `pip install sleap` if you don't plan to use a GPU and this gives you access to the full GUI (where you can create your own dataset, proofread predictions, and export labeled video clips).

**Comment by filos93** [comment]
Wow, thank you so much, I tried that (ie, !python -m sleap.io.visuals path/to/predictions.slp) on Colab and it works perfectly (just sometimes it flickers from an animal to another, but very rarely).

Regarding the GUI, I was trying to use the "Export labeled clip..." option first but I could not, it did not make me select that option in the GUI.
