### ISSUE TITLE
inference with a lot of occlusion / overlap

### ISSUE THREAD

**Issue by sronilsson** [murthylab/sleap#362]
Hi - first SLEAP has been working well for me so far, when I have restricted interactions between animals like in this attached video – looks great, very happy with this one, thanks for your help to get started with this. 

https://drive.google.com/file/d/1hil9rcObtwVt7-kp7G9qyVVVWbbnn82U/view?usp=sharing

I’ve now moved on to other typical experimental videos where two mice are not so friendly with each other – there’s plenty of occlusion, shape shifting and overlap – I am trying to track this video:

https://drive.google.com/file/d/1Q8408t03uaMmMNYgvKqboNth0mfhy8IQ/view?usp=sharing

I’ve done a lot of labelling, and swapped identities are common here, and I frequently get this error concomitant with some frames without predictions, even with suggested skeleton and probably 400-500 labelled images:

INFO:sleap.nn.inference:ERROR in sample index 729
INFO:sleap.nn.inference:{{function_node __inference_Dataset_map_group_instances_5082}} Tried to stack elements of an empty list with non-fully-defined element_shape: <unknown>
         [[{{node TensorArrayV2Stack_15/TensorListStack}}]]

My question, is it possible to use SLEAP alone to get reliable inference in videos like the one with white animals above, with a lot of aggression and occlusion, and no swapped identities?

**Comment by talmo** [comment]
Hi @sronilsson,

Sorry for the delay in responding! It's been a wild week in the world.

The first video looks awesome! Glad to see it working :)

As for the second video, right, this is definitely an issue with the tracking and situations where the animals do a lot of circling. We're working on an improved solution, but one thing you can do for now is to increase the number of frames you use in the window for the tracker, as well as using the flow method.

That error appears when no skeletons can be found in a particular frame, so it contributes a lot to this problem. If there's not instance detected in a couple of frames, it becomes harder to associate the ones before/after the gap. Another thing to do would be to reduce this occurrence of this error. I see the video seems to be lower resolution (if not, disregard this) but one thing you could do is try to tweak the network hyperparameters, namely setting the backbone's **max stride** to **16** and **filters** to 24, and/or decreasing the **output stride** by half (4 -> 2, 8 -> 4).

If you're still not getting good results, shoot me an email (`talmo@princeton.edu`) with the training package exported if you don't mind and I'll have a closer look.

Cheers,

Talmo

**Comment by sronilsson** [comment]
Thanks @talmo - good point about the stride and filters - the resolution is decreased in the video with the white animals - I will give it a go

**Comment by calebvogt** [comment]
Hi folks, I found this thread while also struggling with some swapped identity issues with SLEAPv1.1.3. I implemented the above suggestions on a bottom up model trained on two mice freely interacting (lots of following and circling behavior, so likely a similar situation to @sronilsson ), and I immediately noticed an improvement in maintaining track identities when the mice were circling each other, which previously had been a major source of swapped identities. 

However, the identities are still commonly swapped when the two mice are following each other in a straight line, especially when one mouse is about 10-20 frames behind the first mouse and following in the path/track of the first mouse. Fortunately, these can be fairly easily identified by using velocity suggestions, but in a 15 minute video I am still getting something on the order of >100 swaps. I have experimented with increasing the tracking window from 20 to 60 frames, but this seems to have made the issue worse. I had bumped it to 20 following the suggestions outlined above, but perhaps dropping it back down to 5 would be best? 

Please let me know if you have any suggestions re: altering the training/inference parameters that might help here!

I've emailed my exported training package to you @talmo, thanks in advance for your help here. Happy to share other  project details if needed.

**Comment by talmo** [comment]
Hi @calebvogt,

I copied this to a new issue thread so we can follow up with some discussion over there instead of reviving this old thread: #544

I'll add some notes over there briefly.
