### ISSUE TITLE
Issues using SLEAP ubuntu 20.04

### ISSUE THREAD

**Issue by vspinni** [murthylab/sleap#369]
Have Tensorflow installed and followed the steps for installing provided on the sleap.ai website, however lack of a library is causing problems for utilization of a local GPU when using the sleap GUI. 
![Screenshot from 2020-06-26 19-40-52](https://user-images.githubusercontent.com/26972473/85910528-03f4f380-b7e5-11ea-98ae-5951006240dc.png)

**Comment by talmo** [comment]
Hi @vspinni,

This is just a warning and shouldn't prevent usage of the GPU itself. [You can follow these instructions](https://stackoverflow.com/a/60368453/1939934) for enabling TensorRT support, but it's not strictly necessary.

If you want to check if the GPU is being utilized, open a separate terminal window and install `gpustat`:
`pip install gpustat`
And monitor the GPU usage with:
`gpustat -cp --watch`

Closing this issue but feel free to reopen it and let us know if you're still having problems or don't see the GPU being used.

**Comment by vspinni** [comment]
I tried the commands and they  show that my GPU is not being used. Also tried using nvidia-smi and the same information was displayed.
![Screenshot from 2020-06-30 18-21-06](https://user-images.githubusercontent.com/26972473/86186446-ba671a00-bafe-11ea-9f3c-58570d402b0a.png)

**Comment by talmo** [comment]
Hey @vspinni,

Did you ever get the GPU acceleration to work on your system?

If not, could you try it with cuda 10.1 instead of 10.2?
```
sudo apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1 \
    libnvinfer-dev=6.0.1-1+cuda10.1 \
    libnvinfer-plugin6=6.0.1-1+cuda10.1
```

**Comment by talmo** [comment]
Closing this for now, but @vspinni feel free to re-open if you're still having issues after trying the recommendations above.
