### ISSUE TITLE
An error occurred when attempting to save: No file format adaptor could write this file

### ISSUE THREAD

**Issue by alexkiani** [murthylab/sleap#370]
I am trying to save a project and changing the filename or format does not work. I haven't been able to find any cases with this issue and I am wondering what could be the trouble and how to get it fixed. This is on Linux. Thanks!

**Comment by ntabris** [comment]
When you save, make sure the filename ends with `.slp` and let me know if that gets rid of the problem. (We need better error checking for this...)

**Comment by alexkiani** [comment]
It works, thanks!

**Comment by ntabris** [comment]
Great, thanks for bringing this to our attention! I've added code so that the file extension is automatically added to the file name when needed.
