### ISSUE TITLE
AttributeError: module 'numpy.random' has no attribute 'default_rng'?

### ISSUE THREAD

**Issue by alexkiani** [murthylab/sleap#373]
I am getting this error when trying to run training.py: sleap_env/lib/python3.6/site-packages/sleap/nn/data/training.py. I have tried updating numpy to the latest version and running different aliases for np.random, however no matter what I try I am unable to get default_rng recognized as an attributed. This works on MacOS but not on Linux. Any ideas what to do?

Thanks in advanced!

**Comment by ntabris** [comment]
Hi, @alexkiani. Sorry to hear you're getting an error! I don't think the error message got copied into your message—could you add it?

**Comment by alexkiani** [comment]
Sure thing, here is what I am getting. Let me know if you need anything else!

![Screen Shot 2020-07-02 at 6 13 42 PM](https://user-images.githubusercontent.com/30673344/86421794-17dea080-bc90-11ea-9560-85fec181ecbb.png)

**Comment by ntabris** [comment]
Thanks! Looks like we need to require a newer version of numpy than we had.

What do you see if you run `python -c "import numpy; print(numpy.__version__)"` ?

Not sure how you updated numpy but you could try `conda install numpy=1.18` if that's not what you already did and see if it changes anything.

**Comment by alexkiani** [comment]
Thanks a lot for getting back to me! Running that command I get 1.19.0;

unfortunately `condo install numpy=1.18` doesn't seem to fix the issue.

**Comment by talmo** [comment]
Hi @alexkiani,

From the terminal, could you try this:
```
conda activate sleap_env
pip install numpy==1.18.1
```

Then you can do a quick test independent of SLEAP by running:
```
python -c "import numpy; print(numpy.random.default_rng().choice(1))"
```
If numpy was installed correctly, you should not see an error. Then you can go ahead and try running through with SLEAP again.

Let us know if that works for you :)

**Comment by alexkiani** [comment]
It worked. Thank you!

**Comment by talmo** [comment]
Dope, feel free to open another issue if you run into any other problems.
