### ISSUE TITLE
Not being able to SAVE project

### ISSUE THREAD

**Issue by dlgiant** [murthylab/sleap#376]
Saving in Ubuntu 20.04 is giving the error:
![image](https://user-images.githubusercontent.com/11543575/87337665-d2349a00-c511-11ea-9e10-c1596a133ab1.png)

I get the same error for saving as json and zip.
Dynamics libraries are successfully installed and the log doesn't show any error, including when saving.

**Comment by dlgiant** [comment]
Sorry, the developer version came with the .slp termination and it worked as expected. I believe it must be the same for the non-dev version.

**Comment by ntabris** [comment]
Hi, @dlgiant. Glad you got that working! It sounds like this is an issue that was recently fixed (in v1.0.6). Let us know if you have any other issues!
