### ISSUE TITLE
Trouble generating tracks

### ISSUE THREAD

**Issue by alexkiani** [murthylab/sleap#380]
I was unable to generate tracks on suggested frames through the inference pipeline. I was getting "ValueError: Could not detect backend for specified filename." I was told that the tracker assumes it's running on a contiguous range of frames, which was probably why I couldn't run this on suggested/labelled frames. However, I then tried running it on the entire video hoping that it would at least give me something, but I only got inferences and no tracks were generated.

**Comment by talmo** [comment]
Hi @alexkiani,

Did you run this through the GUI -> Run Inference... -> setting the tracking method + Predict on "entire video"?

To be clear, the tracks are denoted in several places in the GUI by default:
![image](https://user-images.githubusercontent.com/3187454/88183567-a1ceb900-cbff-11ea-8ad9-ed3a97877ad8.png)

And the instances will be colored by the track if you select this menu option:
![image](https://user-images.githubusercontent.com/3187454/88183644-b90da680-cbff-11ea-9573-27a8b72d84bb.png)

**Comment by ntabris** [comment]
I suspect the "ValueError: Could not detect backend for specified filename" in inference means that one of the cli params (`--foo bar`) sent from the GUI is wrong and it's being parsed as a video filename (i.e., if `--foo` isn't a valid arg or doesn't take a value, then `bar` would be interpreted as a video filename).

We should make sure the args shown in https://github.com/murthylab/sleap/issues/374#issuecomment-660287522 are all valid.

**Comment by alexkiani** [comment]
Thanks for the response. I did run it on the entire video and I didn't run into any errors.  But I only got the inferences without track identities. I did notice that my prediction score is a lot higher. I suppose usually higher prediction score is better but maybe it is defined differently here? Not sure if it is relevant to generating tracks but could that be the problem here?
![Screen Shot 2020-07-23 at 4 17 01 PM](https://user-images.githubusercontent.com/30673344/88347759-61a32f80-cd00-11ea-8a66-57ac838e35fe.png)

**Comment by talmo** [comment]
Hi @alexkiani,

So do you have more than 1 animal in this video?

**Comment by alexkiani** [comment]
there's only one animal

**Comment by talmo** [comment]
Ah okay! So in this case there should only be one instance per frame assuming you trained in "single animal" mode. In this case, there is no need for tracks since there is a unique animal identity across time. Tracking serves the purpose of linking predicted instances across time when there are multiple animals.

Basically, you can just use the predicted instance in each frame as is without running the additional tracking step.

Is there something you're trying to do with these predictions that you can't without having the Track field filled?

**Comment by alexkiani** [comment]
I was just trying to follow the tutorial, but all good now. Thanks!
