### ISSUE TITLE
Is there a different way than drag and drop for annotating the landmarks?

### ISSUE THREAD

**Issue by monajalal** [murthylab/sleap#385]
I am noticing that it's quite cumbersome for me to drag and drop landmarks in sleap-label GUI to the associated parts in the animal for labeling it. Is there an easier way for doing so such as the one in DeepLabCut by right-clicking on the keypoint and moving on to the next?

**Comment by talmo** [comment]
Hi Mona,

To be clear on this feature functionality: do you mean that you right click _on the image_ and it moves the current keypoint to that pixel?

We had a mode that worked like this in an internal version but it wasn't too popular among our alpha testers so we didn't keep it, but maybe I'm misunderstanding how this would work (especially with multiple animals).

Do you mind providing a little more information on this feature?

Thanks!

**Comment by talmo** [comment]
I'll close this for now until we hear back on this feature request.
