### ISSUE TITLE
Issue during Colab training.

### ISSUE THREAD

**Issue by DorianBattivelli** [murthylab/sleap#386]
Hello, 

I'm running a training on Colab (video .AVI, with 2 mice to be tracked).
The training automatically stopped after 58 epochs (early stopping), and then several error messages appeared: 

<img width="1131" alt="Schermata 2020-07-26 alle 12 11 55" src="https://user-images.githubusercontent.com/66886884/88476550-7ae2f080-cf39-11ea-87cd-f0a0d934ce5f.png">

Followed by several other error messages, and finally, the cell remains blocked at this stage, but is still running:
<img width="1107" alt="Schermata 2020-07-26 alle 12 12 07" src="https://user-images.githubusercontent.com/66886884/88476569-9817bf00-cf39-11ea-95fe-7f6623400b12.png">

Have you any suggestion about what I should do? 
Thank you, 
best, 
Dorian

**Comment by talmo** [comment]
Hi @DorianBattivelli,

Yes, this is an issue pertaining to the design of the skeleton when using bottom-up training (see https://github.com/murthylab/sleap/issues/357#issuecomment-634956908 for example). This does not happen if you train using the top-down approach.

You can fix this by editing the skeleton and retraining. Sorry about that! We're meaning to make this clearer in the GUI soon (#354).

Basically, what you need to make sure is that the skeleton is a **tree** (no node has two other source nodes) and is **acyclic** (there is no way to get back to the same node from any other node).

Here's a couple of examples, for a skeleton with nodes `A`, `B`, `C`:
- This would not be a tree if you had the connections: `A -> B` and `C -> B`.
- This would not be acyclic if had the connections: `A -> B`, `B -> C` and `C -> A`.

If you'd like to post a screenshot of your skeleton I'm happy to propose one that should work.

Cheers,

Talmo

**Comment by DorianBattivelli** [comment]
Thanks @talmo for that answer, do you want a screen shot of one labeled mouse?

**Comment by talmo** [comment]
Actually, a screenshot of the skeleton nodes and edges in the GUI would be ideal, like this:
![image](https://user-images.githubusercontent.com/3187454/88477324-26298080-cf0d-11ea-80ed-1103e503170a.png)

You can also save it and drop the file here if it's easier :)

**Comment by DorianBattivelli** [comment]
A ok, actually I connected each body part to all the other body parts, so I can't take a picture, the is too long. I thought it was required to do in this way to go ahead ^^

Edges go until 56.
<img width="478" alt="Schermata 2020-07-26 alle 13 05 24" src="https://user-images.githubusercontent.com/66886884/88477499-cb118100-cf40-11ea-95c2-ef15db858c2d.png">

**Comment by talmo** [comment]
Aha, yes that'll be a problem.

Try deleting all your edges and giving these skeleton edges a go:
```
Center1 -> Lateral_left1
Center1 -> Lateral_right1
Center1 -> Tail_base1
Tail_base1 -> Tail_end1
Center1 -> Nose1
Nose1 -> Ear_left1
Nose1 -> Ear_right1
```
(I'm assuming these are all your nodes)

**Comment by DorianBattivelli** [comment]
Thanks @talmo , perfectly clear! 
Best

**Comment by talmo** [comment]
Great! I'll close this issue for now but feel free to re-open if you're still having problems after training. Cheers!
