### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'to_tensor'

### ISSUE THREAD

**Issue by williamcwi** [murthylab/sleap#388]
I got an attribute error when trying to run training

    sleap\env\lib\site-packages\sleap\nn\data\dataset_ops.py:138 unrag  *
        example[key] = example[key].to_tensor(

    AttributeError: 'Tensor' object has no attribute 'to_tensor'

**Comment by talmo** [comment]
Hi @williamcwi,

I've pushed a hotfix that should address this, but do you mind sharing some info on what you were trying to do when you ran into this error?

In the meantime, you can upgrade to an alpha version with this patch with:
```
pip install --upgrade sleap==1.0.9a2
```

**Comment by talmo** [comment]
Closing this but feel free to re-open if still having issues in the new version.
