### ISSUE TITLE
Help with training on a cluster no X11 server

### ISSUE THREAD

**Issue by iteal** [murthylab/sleap#392]
Hi!

Could you help me with using SLEAP to train the network on a cluster without X11 Display?

I get this error:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Is there a parameter I need to set in TrainingJobConfig? 

This is my code:

```python

job_filename = "baseline.bottomup.json"
profile_dir = get_package_file("sleap/training_profiles")
if os.path.exists(os.path.join(profile_dir, job_filename)):
    job_filename = os.path.join(profile_dir, job_filename)
job_config = TrainingJobConfig.load_json(job_filename)

trainer = Trainer.from_config(job_config, training_labels=my_labels, validation_labels=0.1)
trainer.train()

```

Thanks a lot!

**Comment by talmo** [comment]
Hi @iteal,

This is definitely an X issue, but not having an X11 display shouldn't stop it from loading -- we use it on our cluster all the time. Try installing the libraries anyway with:
`sudo apt-get install libx11-xcb1`

If you don't have sudo access or the ability to apt-get could you try `pip install PySide2==5.12.0` and see if that works?

**Comment by iteal** [comment]
Hi @talmo !
I don't have root access and I tried to install this PySide2 version but still no luck. 

A little more log when I set export QT_DEBUG_PLUGINS=1 :

```bash


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/l/laetitia-hebert/miniconda3/envs/sleap_env/bin/platforms" ...
loaded library "/home/l/laetitia-hebert/miniconda3/envs/sleap_env/lib/python3.6/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display localhost:12.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

**Comment by iteal** [comment]
The training is starting now if I set this environment variable before calling my script:

```bash
export QT_QPA_PLATFORM=minimal
```

Is that ok? I am not sure which one to choose in this list of platform plugins.

**Comment by talmo** [comment]
Ah great! Yes, that should be totally fine if it runs and doesn't crash at the end of each epoch (if you have visualizations enabled).

If so, try using this backend for Qt:
```bash
export QT_QPA_PLATFORM=minimal
```

I'll close this but feel free to reopen if it breaks again before the training finishes. Cheers!
