### ISSUE TITLE
Problem with GUI

### ISSUE THREAD

**Issue by mpalrocks** [murthylab/sleap#393]
Hi, thanks for this nice tool.

But I faced some problems. 'Maximize the window' button of the GUI is not functional. That is why, I can not access the lower portion of the GUI, it is cropped out. Neither it is allowing us to minimize the window, so that I can drag that up. Below are the screenshots of server machine. Though I have tried on my local machine too. This problem remains:

![image](https://user-images.githubusercontent.com/37003321/90868445-797bdb00-e3b4-11ea-82bd-18a5dfe1fbf3.png)

![Screenshot from 2020-08-21 13-16-20](https://user-images.githubusercontent.com/37003321/90868087-f2c6fe00-e3b3-11ea-80fc-e64cf9a98351.png)

Let me know if you need any other information. Thanks:)

**Comment by talmo** [comment]
Hey @mpalrocks,

Still not sure what's going on. You could try some of the other backends:
```
export QT_QPA_PLATFORM="wayland"
sleap-label
```
or
```
export QT_QPA_PLATFORM="vnc"
sleap-label
```
or
```
export QT_QPA_PLATFORM="gtk"
sleap-label
```

**Comment by mpalrocks** [comment]
Hi @talmo ! Thanks for helping. But these are not working. As a temporary solution, minimizing the font size of the system and making the server full screen worked for me. Let me know, if you find any solution later.

**Comment by mpalrocks** [comment]
Update: I just found, alt+<clicking at the maximize button> is working for me.

**Comment by talmo** [comment]
Oh excellent! Thanks for updating with the trick to get it working @mpalrocks! I'll close this issue now but feel free to open another one if you run into any other problems.
