### ISSUE TITLE
Error about gcc tools during install on Mac

### ISSUE THREAD

**Issue by vcorbit** [murthylab/sleap#394]
Hello, I am trying to install SLEAP on a Mac running High Sierra (10.13.6). I keep getting the following error:

(sleap_env) Srividhyas-MBP:~ ninjamaster$ pip install sleap
Collecting sleap
  Using cached sleap-1.0.8-py3-none-any.whl (32.4 MB)
Requirement already satisfied: python-rapidjson in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (0.9.1)
Requirement already satisfied: pyzmq in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (19.0.2)
Requirement already satisfied: tensorflow==2.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (2.1.0)

Requirement already satisfied: scikit-learn in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (0.23.2)

Requirement already satisfied: scipy<=1.4.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (1.4.1)

Requirement already satisfied: numpy>=1.18.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (1.19.1)

Requirement already satisfied: cattrs==1.0.0rc in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (1.0.0rc0)

Requirement already satisfied: jsonpickle==1.2 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (1.2)

Requirement already satisfied: attrs==19.3 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (19.3.0)

Requirement already satisfied: pandas in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (1.1.1)

Requirement already satisfied: scikit-video in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (1.1.11)

Requirement already satisfied: networkx in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (2.5)

Requirement already satisfied: imgstore==0.2.9 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (0.2.9)

Requirement already satisfied: PySide2<=5.14.1,>=5.12.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (5.14.1)

Requirement already satisfied: scikit-image in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (0.17.2)

Requirement already satisfied: seaborn in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (0.10.1)

Processing ./Library/Caches/pip/wheels/04/38/eb/73ad6916b8027c8d58b636d8be19457258a87e87836eac528a/jsmin-2.2.2-py3-none-any.whl

Processing ./Library/Caches/pip/wheels/cf/ba/e5/1c5109ab7a67a55df2f9293d99faca4270ec84d787a169e8b6/qimage2ndarray-1.8-py3-none-any.whl

Collecting psutil

  Using cached psutil-5.7.2.tar.gz (460 kB)

Requirement already satisfied: pyyaml in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (5.3.1)

Requirement already satisfied: imgaug==0.3.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (0.3.0)

Requirement already satisfied: pykalman==0.9.5 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (0.9.5)

Requirement already satisfied: h5py in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (2.10.0)

Requirement already satisfied: opencv-python-headless==4.2.0.34 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from sleap) (4.2.0.34)

Requirement already satisfied: protobuf>=3.8.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (3.13.0)

Requirement already satisfied: wheel>=0.26; python_version >= "3" in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (0.35.1)

Requirement already satisfied: google-pasta>=0.1.6 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (0.2.0)

Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (2.1.1)

Requirement already satisfied: astor>=0.6.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (0.8.1)

Requirement already satisfied: grpcio>=1.8.6 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (1.31.0)

Requirement already satisfied: six>=1.12.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (1.15.0)

Requirement already satisfied: gast==0.2.2 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (0.2.2)

Requirement already satisfied: termcolor>=1.1.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (1.1.0)

Requirement already satisfied: wrapt>=1.11.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (1.12.1)

Requirement already satisfied: opt-einsum>=2.3.2 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (3.3.0)

Requirement already satisfied: keras-preprocessing>=1.1.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (1.1.2)

Requirement already satisfied: absl-py>=0.7.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (0.10.0)

Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (2.1.0)

Requirement already satisfied: keras-applications>=1.0.8 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorflow==2.1->sleap) (1.0.8)

Requirement already satisfied: threadpoolctl>=2.0.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scikit-learn->sleap) (2.1.0)

Requirement already satisfied: joblib>=0.11 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scikit-learn->sleap) (0.16.0)

Requirement already satisfied: python-dateutil>=2.7.3 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from pandas->sleap) (2.8.1)

Requirement already satisfied: pytz>=2017.2 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from pandas->sleap) (2020.1)

Requirement already satisfied: pillow in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scikit-video->sleap) (7.2.0)

Requirement already satisfied: decorator>=4.3.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from networkx->sleap) (4.4.2)

Requirement already satisfied: tzlocal in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from imgstore==0.2.9->sleap) (2.1)

Requirement already satisfied: shiboken2==5.14.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from PySide2<=5.14.1,>=5.12.0->sleap) (5.14.1)

Requirement already satisfied: PyWavelets>=1.1.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scikit-image->sleap) (1.1.1)

Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scikit-image->sleap) (3.3.1)

Requirement already satisfied: imageio>=2.3.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scikit-image->sleap) (2.9.0)

Requirement already satisfied: tifffile>=2019.7.26 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scikit-image->sleap) (2020.8.25)

Requirement already satisfied: Shapely in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from imgaug==0.3.0->sleap) (1.7.1)

Requirement already satisfied: setuptools in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from protobuf>=3.8.0->tensorflow==2.1->sleap) (49.6.0.post20200814)

Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (0.4.1)

Requirement already satisfied: google-auth<2,>=1.6.3 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (1.21.0)

Requirement already satisfied: markdown>=2.6.8 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (3.2.2)

Requirement already satisfied: werkzeug>=0.11.15 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (1.0.1)

Requirement already satisfied: requests<3,>=2.21.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (2.24.0)

Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->sleap) (1.2.0)

Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->sleap) (0.10.0)

Requirement already satisfied: certifi>=2020.06.20 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->sleap) (2020.6.20)

Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->sleap) (2.4.7)

Requirement already satisfied: requests-oauthlib>=0.7.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (1.3.0)

Requirement already satisfied: pyasn1-modules>=0.2.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (0.2.8)

Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (4.1.1)

Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (4.6)

Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from markdown>=2.6.8->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (1.7.0)

Requirement already satisfied: chardet<4,>=3.0.2 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (3.0.4)

Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (1.25.10)

Requirement already satisfied: idna<3,>=2.5 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (2.10)

Requirement already satisfied: oauthlib>=3.0.0 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (3.1.0)

Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (0.4.8)

Requirement already satisfied: zipp>=0.5 in ./opt/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1->sleap) (3.1.0)

Building wheels for collected packages: psutil

  Building wheel for psutil (setup.py) ... error

  ERROR: Command errored out with exit status 1:

   command: /Users/ninjamaster/opt/anaconda3/envs/sleap_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-wheel-9lt86ous

       cwd: /private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/

  Complete output (44 lines):

  running bdist_wheel

  running build

  running build_py

  creating build

  creating build/lib.macosx-10.9-x86_64-3.6

  creating build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_pswindows.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_common.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_psosx.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_psbsd.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_psaix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_pslinux.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_compat.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_psposix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  copying psutil/_pssunos.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

  creating build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_contracts.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_connections.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/runner.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_unicode.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_misc.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_posix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_linux.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_sunos.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_aix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_process.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_bsd.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_system.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_osx.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_memleaks.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_windows.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/__main__.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  copying psutil/tests/test_testutils.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

  running build_ext

  building 'psutil._psutil_osx' extension

  creating build/temp.macosx-10.9-x86_64-3.6

  creating build/temp.macosx-10.9-x86_64-3.6/psutil

  creating build/temp.macosx-10.9-x86_64-3.6/psutil/arch

  creating build/temp.macosx-10.9-x86_64-3.6/psutil/arch/osx

  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ninjamaster/opt/anaconda3/envs/sleap_env/include -arch x86_64 -I/Users/ninjamaster/opt/anaconda3/envs/sleap_env/include -arch x86_64 -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_OSX=1 -I/Users/ninjamaster/opt/anaconda3/envs/sleap_env/include/python3.6m -c psutil/_psutil_common.c -o build/temp.macosx-10.9-x86_64-3.6/psutil/_psutil_common.o

  xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.

  error: command 'gcc' failed with exit status 1

  ----------------------------------------

  ERROR: Failed building wheel for psutil

  Running setup.py clean for psutil

Failed to build psutil

DEPRECATION: Could not build wheels for psutil which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

Installing collected packages: jsmin, qimage2ndarray, psutil, sleap

    Running setup.py install for psutil ... error

    ERROR: Command errored out with exit status 1:

     command: /Users/ninjamaster/opt/anaconda3/envs/sleap_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-record-qrx8_2p_/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ninjamaster/opt/anaconda3/envs/sleap_env/include/python3.6m/psutil

         cwd: /private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/

    Complete output (44 lines):

    running install

    running build

    running build_py

    creating build

    creating build/lib.macosx-10.9-x86_64-3.6

    creating build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_pswindows.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_common.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_psosx.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_psbsd.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_psaix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_pslinux.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_compat.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_psposix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    copying psutil/_pssunos.py -> build/lib.macosx-10.9-x86_64-3.6/psutil

    creating build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_contracts.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_connections.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/runner.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_unicode.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_misc.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_posix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_linux.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_sunos.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_aix.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_process.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_bsd.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_system.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_osx.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_memleaks.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_windows.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/__main__.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    copying psutil/tests/test_testutils.py -> build/lib.macosx-10.9-x86_64-3.6/psutil/tests

    running build_ext

    building 'psutil._psutil_osx' extension

    creating build/temp.macosx-10.9-x86_64-3.6

    creating build/temp.macosx-10.9-x86_64-3.6/psutil

    creating build/temp.macosx-10.9-x86_64-3.6/psutil/arch

    creating build/temp.macosx-10.9-x86_64-3.6/psutil/arch/osx

    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ninjamaster/opt/anaconda3/envs/sleap_env/include -arch x86_64 -I/Users/ninjamaster/opt/anaconda3/envs/sleap_env/include -arch x86_64 -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_OSX=1 -I/Users/ninjamaster/opt/anaconda3/envs/sleap_env/include/python3.6m -c psutil/_psutil_common.c -o build/temp.macosx-10.9-x86_64-3.6/psutil/_psutil_common.o

    xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.

    error: command 'gcc' failed with exit status 1

    ----------------------------------------

ERROR: Command errored out with exit status 1: /Users/ninjamaster/opt/anaconda3/envs/sleap_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-install-1hi8gtay/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/t6/6dhv0g7s16d3ty588y3wwfhr0000gn/T/pip-record-qrx8_2p_/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ninjamaster/opt/anaconda3/envs/sleap_env/include/python3.6m/psutil Check the logs for full command output.

It seems that it wants some type of developer tools, but I am not sure the proper way to download those for this to work right. Please advise if you can!
Thanks!

**Comment by talmo** [comment]
Hi @vcorbit,

Sounds like you need `gcc` to be able to compile some of those dependencies. Try typing this in the console:

```
xcode-select --install
```

[Some more info here if that doesn't work on your version.](https://stackoverflow.com/questions/9329243/how-to-install-xcode-command-line-tools) Give it a spin and let me know if you're still having installation issues.

**Comment by davidt0x** [comment]
Hi @vcorbit,

If Talmo's suggestion doesn't work take a look at the suggestions noted in this issue for psutil on MacOS:
[https://github.com/giampaolo/psutil/issues/1632](
https://github.com/giampaolo/psutil/issues/1632) and [https://stackoverflow.com/questions/62417691/failed-building-wheel-for-psutil-on-macos](https://stackoverflow.com/questions/62417691/failed-building-wheel-for-psutil-on-macos). It seems like some people are getting this error when they have two SDK versions installed.

**Comment by ntabris** [comment]
Another thing to try (which is probably a quicker fix if it works) is to do a `pip install psutil==5.7.1` then a `pip install sleap`. It appears that there's a prebuilt mac release of psutil 5.7.1 on pypi but no mac build of 5.7.2. (Fwiw, I have psutil 5.6.7 in the sleap environment on my mac.)

**Comment by vcorbit** [comment]
Hi,

The xcode-select install worked! Thanks so much.

**Comment by talmo** [comment]
Closing this then but feel free to open a now issue if you run into any other problems. Cheers!
