### ISSUE TITLE
Quick-find new inferences for correcting predictions?

### ISSUE THREAD

**Issue by Idavr** [murthylab/sleap#397]
Hi there!

I am in the process of labeling, training, running predictions and correcting the automatic labeling for re-training, but after a while the black lines at the bottom (showing the labeled frames) start clustering together and it is getting more and more difficult to identify what are new predictions (slim lines) among the already labeled frames (thick lines). Is there a quick way to jump to each new prediction?

**Comment by talmo** [comment]
Hi @Idavr,

There is! If you go to Help -> Keyboard Shortcuts you'll see a variety of commands that are helpful for navigation:
![image](https://user-images.githubusercontent.com/3187454/92260792-74378980-eea6-11ea-9e0d-ece23e385bcf.png)

You can use suggestions to make a list of frames to label that you can then skip to, or use the other navigation utilities to skip around.

Let me know if this works or if you had something different in mind. Cheers,

Talmo

**Comment by Idavr** [comment]
Hi @talmo,

I've seen this and unfortunately it does not help for what I meant. The shortcuts work well for jumping to either already labeled frames (thick lines in the bottom timeline for each video) or for user generated suggestions (light-blue lines if unlabeled, dark-blue if labeled), but I can't find any shortcuts for jumping to frames with inferences (done right after training the model) where the labels in the frame are the yellow colour (and thin lines in the bottom timeline). Does this clear up my question?

Best,

Ida

**Comment by talmo** [comment]
Hi @Idavr,

Completely clear -- I'll mark this as a feature request and add it in to the GUI for the next release. Cheers!

**Comment by Idavr** [comment]
Hi @talmo,

Thank you very much, looking forward to the update! :)
