### ISSUE TITLE
Problem when trying top-down/ centroid model training with own data using the Training_and_inference_using_Google_Drive.ipynb

### ISSUE THREAD

**Issue by GECGall** [murthylab/sleap#402]
Hi,

i'm currently trying out sleap using the CoLab notebooks provided by you, specifically the Training_and_inference_using_Google_Drive.ipynb, but using my own data on it (it works for the data provided by you). For the bottom-up training model all works fine (as far as I can tell) but when I try the top-down or centroid model on my own data,  I get the following error (in both): 

"ValueError: 'thorax' is not in list"

where the the line of code I ran was : 
!sleap-train baseline.topdown_confmaps.json GG_label.pkg.slp --run_name "colab_demo.topdown_confmaps"

Is there something I should change, and if so what, or is this a problem with the program expecting to find specific nodes for the individuals which are non-existent (my nodes have different names and thorax, abdomen, etc)?

any help would be greatly appreciated!

best,
Gabriella

**Comment by talmo** [comment]
Hi @GECGall,

So the `baseline.topdown_confmaps.json` file contains the model configuration. The easiest way to configure it when training on your own data is to set up the training configuration in the GUI and save out the JSON files. You can do this by going to SLEAP GUI menu -> **Predict** -> **Run Training** -> **Save configuration files...**:

![image](https://user-images.githubusercontent.com/3187454/92813658-9db55100-f38f-11ea-9f15-9eacb93ae4b8.png)

The anchor part in a top-down model is a body part that is used as a reference point when cropping around each animal:
![image](https://user-images.githubusercontent.com/3187454/92813744-ce958600-f38f-11ea-85ce-805cc2779165.png)

You can find more info on this approach in [section 3.3 of our preprint](https://www.biorxiv.org/content/10.1101/2020.08.31.276246v1.full.pdf).

If you're comfortable with Python and working in a notebook environment, you can also follow along with [this tutorial](https://github.com/talmo/sleap-mit-tutorial#tutorial) which walks you through how to configure the model training without the GUI or uploading JSON files.

Let me know if you're still having issues or if you have any questions!
