### ISSUE TITLE
Extracting coordinates; hdf5 to csv

### ISSUE THREAD

**Issue by nachonacho2** [murthylab/sleap#403]
Is it possible to export the tracked node coordinates to a flexible format like csv?
I am having difficulty utilising the data within the hdf5 files (I am not familiar with MATLAB). I can see the tracks data I want using ViTables but because this is in a carray it is unable to export it.

For example, for a two animal video, each with a tracked skeleton of 3 nodes (head/thorax/abdomen), I would like the x,y coordinates for the thorax node from each animal for each frame.

**Comment by talmo** [comment]
Hi @nachonacho2,

It's possible to load either the project files (`.slp`) or the exported HDF5 files (`.h5`) in Python, including to generate some CSVs.

Here's a little example notebook on Colab that should help:

[**`Converting SLEAP Analysis HDF5 to CSV.ipynb`**](https://colab.research.google.com/drive/13Mt5we4keXRbMwJPXSjEogVucrqh81GF?usp=sharing)

You can run that notebook directly on Google Colab by following the steps I wrote out to upload your own data.

Let me know if you have any issues or questions on how to use the example! :)

**Comment by nachonacho2** [comment]
Hi @talmo,
Thank you very much for your prompt and incredibly helpful reply! Your example notebook covers exactly what I was after.
Cheers :)
