### ISSUE TITLE
Error preventing Export HD5 

### ISSUE THREAD

**Issue by raufai02** [murthylab/sleap#404]
Hi, 
I have a large .slp file full of predicted instances. I would like to generate a corresponding h5 dataset but have been unable to using the GUI. I consistently get the following output. 

"
ignoring 1 empty tracks
Killed
"
Some guidance on this issue would be appreciated.

**Comment by talmo** [comment]
Hi @raufai02,

Would you mind providing a little more info on your data file? How many videos/tracks/instances are there in the labels?

Or preferably, if you don't mind, sharing a link to the .slp file? You don't have to share the raw data, just the .slp file with the tracks so I can check it out.

Thanks!

Talmo

**Comment by raufai02** [comment]
Hi, 

The file is quite large— data collected on a many hour video, with a large number of instances( I did not feed a parameter for how many tracks to include, so it created new tracks very frequently.). 
.slp isn't a supported file type to share on github, so how can I send you the file?

Thanks, 
Rauf

**Comment by talmo** [comment]
Closing this stale issue and tracking the progress of being able to export very large analysis files in #443.
