### ISSUE TITLE
Tracking predictions

### ISSUE THREAD

**Issue by Idavr** [murthylab/sleap#405]
Hi there,

I am playing around with the different ways of proofreading and getting a solid model trained up, and I just now wanted to see how the Tracking would look like when predicting with the most recent iteration of a model (I just now switched trying to use bottom-up instead of top-down based on what I read in your article). If I have misunderstood I apologize in advance, but from what I gathered one should be able to use the Tracking function to see how the different instances (or nodes? I am a bit uncertain now suddenly...) shift across x-numbers of frames, correct? What made me a bit confused is that I don't see any of these types of trails when going over the Predictions (to adjust and re-train the model), but when I adjust a node in an instance (for example the nose on my rat skeleton), there suddenly appears a track from where the node initially was placed and to where I manually placed it the second I go back and forth one frame. Also, this only happens for this one specific node (i.e., the nose), irrespective of whether I adjust any other nodes. The tracking only follows "Nose"... This doesn't match with me thinking they would track across multiple frames, so could you please correct me if (and where) I am wrong?

Also, note that the predictions from the inference step (done manually after training) are distributed randomly, so there are rarely two consecutive frames with instances in them. Is that a requisite?

Best,

Ida

**Comment by talmo** [comment]
Hi @Idavr,

I'm guessing you figured this out from the edits but feel free to reopen if you still need any clarifications!

Cheers,

Talmo
