### ISSUE TITLE
Worse inferences when predict on entire video?

### ISSUE THREAD

**Issue by lexiiizhou** [murthylab/sleap#411]
I noticed that when I run inferences on even 3000 suggested frames the predictions I got were a lot better than when I run inference on the entire video (20000+ frames). I also noticed that even for similar frames, suggested frames generate a relatively accurate prediction while entire video can give something completely off. I wonder if these two are computed differently or if it is just a bias from my observation? Is there anyway I can fix it?

**Comment by talmo** [comment]
Hi @lexiiizhou,

That definitely sounds like a bug.

How far off are the predictions when you do it on the entire video? Do you see reasonable poses but they're not overlapping with the animal?

Were you also running the tracker?

Could you try the following:

1. Select the whole video by holding Shift + drag on the seekbar, like this:
![image](https://user-images.githubusercontent.com/3187454/96385930-2381a480-1165-11eb-9835-63f44c636eb0.png)

2. Run inference but now choose "selected clip" for predict on, like this:
![image](https://user-images.githubusercontent.com/3187454/96385944-34cab100-1165-11eb-8edd-45d92c54be2a.png)

Let me know if you get different results than if you predict on the whole video.

Cheers,

Talmo

**Comment by lexiiizhou** [comment]
Hi,

I am only running single animal so I am not running trackers. I did what you said and the predictions I got were similar to those that entire video generates. And yes they do seem like plausible pose but just are not overlapping well with the animal. 
![Screen Shot 2020-10-18 at 2 53 57 PM](https://user-images.githubusercontent.com/68297823/96386730-e95ad780-1151-11eb-9538-b11563a4d948.png)

For reference, this is what suggested frames generates (not the same frame but a similar one):
![Screen Shot 2020-10-18 at 3 00 19 PM](https://user-images.githubusercontent.com/68297823/96386833-b107c900-1152-11eb-82b2-2f5080205ad5.png)

Best,
Lexi

**Comment by talmo** [comment]
Gotcha. This might be the same issue as #374 strangely.

A few questions:

1. What version of SLEAP are you on? (It shows on the title bar of the GUI)
2. What operating system are you on?
3. What is the filename of the video?
4. Could you copy the command that appears in the terminal when you go to predict -> run inference -> entire video? It starts with `Command line call: sleap-track...`

**Comment by lexiiizhou** [comment]
1. I couldn't find the version but I downloaded it around July. 
2. Linux
3 & 4 (video filename included in the common line call: D231ELT ...nalgene.avi): 
![Screen Shot 2020-10-18 at 3 37 13 PM](https://user-images.githubusercontent.com/68297823/96387573-ef53b700-1157-11eb-848b-38aa42d5cc91.png)

**Comment by talmo** [comment]
Ok, two things to try:

1. Try tracking from the CLI directly:
```
sleap-track "/home/wholebrain/Desktop/Sleap/dreadd rotation videos/D231ELT_cno1mgkg_nalgene.avi" -m "/home/wholebrain/Desktop/Sleap/models/dr201018_140622.single_instance.9796/training_config.json" -o "/home/wholebrain/Desktop/Sleap/dreadd rotation videos/D231ELT_cno1mgkg_nalgene.avi.test.slp"
```

Then check out the predictions in the GUI:
```
sleap-label "/home/wholebrain/Desktop/Sleap/dreadd rotation videos/D231ELT_cno1mgkg_nalgene.avi.test.slp"
```

Let me know how those look and if you're getting the same issue.


2. Update sleap and try again (from the GUI or CLI): `pip install --upgrade sleap`

You should see v1.0.9 in the title bar of the GUI, or by typing: `pip freeze | grep sleap`

**Comment by lexiiizhou** [comment]
Hi,

I updated sleap and also tried the first method. This time I noticed that the first 2500ish frames got good predictions but after that the same problem occurred. Sometimes a few consecutive frames(different) would get the same inference.

**Comment by lexiiizhou** [comment]
Ok so I think the predictions might not be the problem. When I go through the frames. with -> key some of the predictions after 2500 frames they seemed alright. However, when I click on the seekbar to jump to a specific frame that I just went through the inferences show up at the wrong place. I then generated a labelled video and the inferences seemed fine. This is no longer an issue for me because I can still use the data but maybe there is some display problem?

**Comment by talmo** [comment]
Aha! That's an issue with seekability.

This happens because some video codecs will save space by only storing partial frames between keyframes, so readers need to find the closest keyframe and reconstruct the desired frame, sometimes leading to different images depending on the frame you were on before. You usually won't notice this when playing the video normally, but for applications like these it becomes a problem since we go frame-by-frame in potentially random order. You can check out [this blog post](http://blog.loopbio.com/video-io-1-introduction.html) for a more in-depth explanation, but basically you just have to convert your video into a format that allows reliable frame accurate seeking.

Anyway, here's the command you can use:
```
ffmpeg -i "input.avi" -c:v libx264 -preset superfast -pix_fmt yuv420p "output.mp4"
```
Replace the filenames with your video and try to predict on the converted file. You should be able to get consistent results now, but let me know if you don't.

**Comment by lexiiizhou** [comment]
ah I see. Thanks!
