### ISSUE TITLE
Importing maDLC labels

### ISSUE THREAD

**Issue by raufai02** [murthylab/sleap#412]
Hi, 

We have a large set of manually labeled frames used in social DLC. Is there a way to train a model with SLEAP using these labeled frames? It would be a bit of a tall task to re-label all of these frames manually. 

Thanks, 

Rauf

**Comment by ntabris** [comment]
Hi, @raufai02.

Have you tried using the "Import..." command in the GUI? You can use it to import either the DLC CSV file (data for single video) or YAML file (for an entire project).

**Comment by raufai02** [comment]
I am aware of this feature but I don’t know if I fully understand how to use it - can I simply add a DLC .csv file and immediately “run training” on the imported data?

**Comment by ntabris** [comment]
Assuming the import works, then once you save the SLEAP project w/ the imported data then you should be ready to run training.

**Comment by raufai02** [comment]
Ok, thank you.

**Comment by raufai02** [comment]
I get the error "No file format adaptor could write this file" when I try to save a file with DLC .csv imported labeled data. What can I do to be able to save the file?

**Comment by ntabris** [comment]
Does the new filename end in `.slp`? If not, it should. Otherwise, maybe try using “save as” instead of “save”.

By the way, does the imported data look good?

**Comment by raufai02** [comment]
I have been trying to save as a .slp and tried both "save as" and "save". It seems the error occurs not when I try to save but when I am importing the data Here is the terminal error output when I try to import a DLC file: 


```
Empty filename passed to function
Traceback (most recent call last):
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 216, in importDLC
    self.execute(ImportDeepLabCut)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 184, in execute
    command().execute(context=self, params=kwargs)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 93, in execute
    self.do_with_signal(context, params)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 117, in do_with_signal
    cls.do_action(context, params)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 615, in do_action
    labels = Labels.load_deeplabcut(filename=params["filename"])
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/io/dataset.py", line 1431, in load_deeplabcut
    return read(filename, for_object="labels", as_format="deeplabcut")
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/io/format/__init__.py", line 58, in read
    return disp.read(filename, *args, **kwargs)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/io/format/dispatch.py", line 49, in read
    return adaptor.read(file, *args, **kwargs)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/io/format/deeplabcut.py", line 57, in read
    return Labels(labeled_frames=cls.read_frames(file, full_video, *args, **kwargs))
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/io/format/deeplabcut.py", line 95, in read_frames
    skeleton.add_nodes(node_names)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/skeleton.py", line 450, in add_nodes
    self.add_node(node)
  File "/home/rauf/.conda/envs/sleap_env/lib/python3.6/site-packages/sleap/skeleton.py", line 435, in add_node
    raise ValueError("Skeleton already has a node named ({})".format(name))
ValueError: Skeleton already has a node named (Vole1)
```

With regards to how the data looks, I haven't gotten any visible output so far.

**Comment by talmo** [comment]
Hi @raufai02,

Is this a multi-instance (maDLC) dataset?

Do you mind sharing the .csv file in the project you're trying to import? You can attach it here or send it to talmo@princeton.edu.

Thanks!

**Comment by raufai02** [comment]
Yes, there are two instances in each frame. I want to import and train using several labeled datasets but I can send the first one I was trying to import.

**Comment by talmo** [comment]
Just a quick update: I'm working on this, but this is a bit of a change since this requires supporting the new multi-animal DLC format. Will reply here when we have a new version ready. Thanks for sending the test data!

**Comment by talmo** [comment]
Hi @raufai02,

I've pushed an alpha version with multi-animal DLC labels support. Try importing the CSV file with the new version from here:
https://github.com/murthylab/sleap/releases/tag/v1.0.10a6

Let me know if that works for you or if you see any issues when you import!

**Comment by talmo** [comment]
Now implemented in [SLEAP v1.0.10a7](https://github.com/murthylab/sleap/releases/tag/v1.0.10a7) and will be in the next release (v1.0.10).

**Comment by raufai02** [comment]
Hi again.  I am using v1.0.10a9 and it can open maDLC .csv files, which is great! However, it opens a new GUI window for each file I try to import. How can I have a .slp file that I can train on numerous maDLC labeled datasets?

**Comment by talmo** [comment]
Hi @raufai02,

I see. Do you have many CSV files?

One thing you can do for now is to import each CSV, save them out to their own `.slp` file, then open the first one and merge the other ones into the same project.

I'll re-open this issue so I remember to add the ability to select multiple DLC files for import.

**Comment by talmo** [comment]
From https://github.com/murthylab/sleap/issues/429#issuecomment-744749720:
> Just as a piece of future reference until we implement this functionality natively, here's how you can import and merge a set of DLC folders:
> 
> ```python
> import sleap
> from glob import glob
> 
> 
> csv_files = glob("labeled-data/*/*.csv")
> merged_labels = None
> for csv_file in csv_files:
>     labels = sleap.Labels.load_file(csv_file, as_format="deeplabcut")
>     if merged_labels is None:
>         merged_labels = labels
>     else:
>         merged_labels.extend_from(labels, unify=True)
> 
> print("Merged labels:")
> merged_labels.describe()
> 
> merged_labels.save("merged_labels.slp")
> merged_labels.save("merged_labels.pkg.slp", with_images=True)  # comment this out to skip saving with embedded images
> ```
> 
> This assumes a folder structure like this:
> 
> ```
> labeled-data/
>     video1/
>         my_labels.csv
>         img00000.png
>         img00001.png
>         ...
>     video2/
>     ...
> ```

**Comment by raufai02** [comment]
This is very very helpful, thanks!

**Comment by raufai02** [comment]
What is the difference between the file with embedded images (the .pkg.slp ) vs the smaller file (.slp)?

**Comment by talmo** [comment]
Hi @raufai02,

The file with embedded images (`.pkg.slp`) is a "training package". This file will be much bigger as we include the images inside of the project file so you can upload it to Colab or wherever for training remotely without having to have access to the original data.

 If you're just working locally, you can just stick with the regular `.slp` file for opening it within the SLEAP labeling GUI.

**Comment by ariematsliah-princeton** [comment]
Hi @raufai02 
We now support importing a folder with multiple DLC files from the GUI (included in the latest SLEAP [release](https://github.com/murthylab/sleap/releases/tag/v1.1.0))

Closing this for now, please reopen if you encounter additional issues.
