### ISSUE TITLE
Labeled Frames Missing in GUI After Training

### ISSUE THREAD

**Issue by sesmith5340** [murthylab/sleap#413]
I am having issues with my labeled frames disappearing after successfully training a model (the last two times).  Initially, I labeled 20-30 frames, trained a bottom-up model, and predicted on "random frames".  Using these predictions, I labeled another 300 frames then ran a bottom-up model predicting on "suggested frames".  After training was complete, the model predicted on 3000+ frames but only 15 labeled frames were left in the dataset.  Using these predictions, I labeled another 400 frames but this time saved out the dataset to a different file (so I wouldn't lose them) and, again, ran the training using a bottom-up model with predicting on "suggested frames".  After training was complete, there were only 31 labeled frames showing in the GUI with 4286 predicted frames.  Also, I ran sleap-inpect on the before and after .slp files; it confirms what is showing in the GUI that most of the user labeled frames are gone.  See screen shot.  Is this suppose to happen?

I am running Windows 10 with SLEAP version 1.0.9 and no NVIDIA GPU.

![image](https://user-images.githubusercontent.com/37842525/97433983-b902fe00-18f4-11eb-9161-88cf46c310ca.png)

**Comment by talmo** [comment]
Hi @sesmith5340,

Sorry to hear about your data loss! That's a serious problem!

Could you tell me a bit more about your training workflow? You mentioned that you don't have a NVIDIA GPU, so have you been exporting a training package to train remotely or have been just training on the CPU?

If you don't mind, shoot me your `.slp` files to talmo@princeton.edu (no need for the video) and I'll have a closer look at what might be going on with your project file.

**Comment by sesmith5340** [comment]
Thanks for the quick response. @talmo   I've just been training on the CPU by letting it run overnight...so the entire workflow is within the GUI with a sequence as outlined in the initial post.  I sent the two .slp files referenced above.

**Comment by talmo** [comment]
Hi @sesmith5340,

I think I found the issue. Could you give this alpha build a spin?

You can install it into a new environment like this:
`conda create -n sleap_alpha -c sleap/label/dev sleap=1.0.10a5`

Then `conda activate sleap_alpha` and use it as you would normally. Let me know if you still have missing labels after inference (or if you have trouble installing the alpha version).

Cheers!

**Comment by sesmith5340** [comment]
@talmo ,

I ran the 1.0.10a5 last night on the same dataset and it looked good when I checked this morning.  All the labeled frames were retained.  Thank you for the quick fix.
