### ISSUE TITLE
"Fit Instances to View" when there are no instances

### ISSUE THREAD

**Issue by smidm** [murthylab/sleap#416]
In sleap-label when View -> Fit Instances to View is checked and a frame with no instances is selected the view zooms to top left corner.

It should probably keep the previous view zoom settings.

Anyway the results of SLEAP are awesome! I've got almost perfect ants 3 point pose estimation with as few as 20x6 training examples. Also the GUI is very professional and easy to work with. This is almost never the case with software packages developed in academia. Thank you very much.

**Comment by talmo** [comment]
Cheers @smidm!

I'll tag this is an enhancement for now -- the ideal behavior should probably be to reset the zoom state as you suggest. We generally use the "fit to instances" when we already have predicted instances and we're going through them quickly.

**Comment by smidm** [comment]
I would prefer to keep the previous zoom settings for my use case. I was labelling 20 random frames and in some cases all the points are not recognizable from a static image. I needed to see few frames before and after to figure out the correct labelling.

**Comment by talmo** [comment]
Now implemented in [SLEAP v1.0.10a7](https://github.com/murthylab/sleap/releases/tag/v1.0.10a7) and will be in the next release (v1.0.10).
