### ISSUE TITLE
Can't export .slp to hdf5

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#431]
Hi
I'm trying to export the inference .slp file to .csv or hdf5.  I found your python notebook that converts .h5 files to .csvs, but I can't seem to get the GUI to save the .slp file as hdf5.  

Here's the error

```
(sleap_env) cat@cat-GF63-Thin-9SCX:~/code$ sleap-label
2020-12-09 11:28:13.690700: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-12-09 11:28:13.693799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/shiboken2/files.dir/shibokensupport/signature/parser.py:97: FutureWarning: split() requires a non-empty pattern match.
  return [x.strip() for x in split(argstr) if x.strip() not in ("", ",")]
Traceback (most recent call last):
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 284, in exportAnalysisFile
    self.execute(ExportAnalysisFile)
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 232, in execute
    command().execute(context=self, params=kwargs)
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 129, in execute
    self.do_with_signal(context, params)
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 153, in do_with_signal
    cls.do_action(context, params)
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/gui/commands.py", line 825, in do_action
    SleapAnalysisAdaptor.write(params["output_path"], context.labels)
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/io/format/sleap_analysis.py", line 126, in write
    write_analysis(source_object, output_path=filename, all_frames=True)
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/info/write_tracking_h5.py", line 192, in main
    labels, all_frames
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/info/write_tracking_h5.py", line 94, in get_occupancy_and_points_matrices
    locations_matrix[frame_i, ..., track_i] = inst_points
ValueError: could not broadcast input array from shape (11,2) into shape (6,2)
```

**Comment by catubc** [comment]
Actually, seems like command line is working.

So for a inference file from a 10000 frame video, if I run this:
```
>>> import sleap
>>> data = sleap.load_file('/home/cat/Downloads/sleap_video.mp4.slp')
>>> print (len(data))
10000

```

Seems that data has all the information we need.

Thanks

**Comment by catubc** [comment]
Sorry, it seems there is too much wrapped info there. 

How do I save the data to .hdf5 from here? 
```



>>> print (data[0][0])
PredictedInstance(skeleton=<sleap.skeleton.Skeleton object at 0x7fb2e40d9ba8>, track=None, from_predicted=None, _points=array([(         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        ),
       (644.43603516, 16.54469299,  True, False, 0.25470021),
       (         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        ),
       (         nan,         nan,  True, False, 0.        )],
      dtype=(sleap.instance.PredictedPoint, [('x', '<f8'), ('y', '<f8'), ('visible', '?'), ('complete', '?'), ('score', '<f8')])).view(numpy.recarray), _nodes=[Node(name='nose', weight=1.0), Node(name='leftear', weight=1.0), Node(name='rightear', weight=1.0), Node(name='spine1', weight=1.0), Node(name='spine2', weight=1.0), Node(name='spine3', weight=1.0), Node(name='spine4', weight=1.0), Node(name='spine5', weight=1.0), Node(name='tail1', weight=1.0), Node(name='tail2', weight=1.0), Node(name='tail3', weight=1.0)], frame=LabeledFrame(video=Video(backend=MediaVideo(filename='/home/cat/Downloads/sleap_video.mp4', grayscale=False, bgr=True, dataset='', input_format='')), frame_idx=0, _instances=[..., PredictedInstance(skeleton=<sleap.skeleton.Skeleton object at 0x7fb2e40d9ba8>, track=None, from_predicted=None, _points=array([(248.54299927,  -3.56504822,  True, False, 0.20429371),
       ( 17.06147003, 124.55924988,  True, False, 0.23641443),
       (         nan,          nan,  True, False, 0.        ),
       (         nan,          nan,  True, False, 0.        ),
       ( 84.5176239 ,  24.53610229,  True, False, 0.3144469 ),
       (         nan,          nan,  True, False, 0.        ),
       (         nan,          nan,  True, False, 0.        ),

```

**Comment by talmo** [comment]
Hi @catubc,

Give it a go with the .h5 file generated by **File** -> **Export Analysis HDF5...** or by running `sleap-convert --format analysis "/home/cat/Downloads/sleap_video.mp4.slp"`.

This file doesn't contain any of the SLEAP metadata that might be harder to parse when reading from another program.

**Comment by catubc** [comment]
Hi Talmo
Thanks for the help. I've now converted both a feature only and feature+assembly .slp file.

However, the labeling looks pretty random, even though I thought inference seemed reasonable in the GUI for previous analysis.  Here's the output video for the feature inference only:

https://drive.google.com/file/d/1pWq1fBURp_GZouH2Id2OG8hl3l67k4X2/view?usp=sharing

I'm generating these movies by grabing track info as follows. Is there something I'm doing wrong?  I can also start a separate issue if you wish.

```
# LOAD h5 file:
filename = '/home/cat/Downloads/sleap_video.mp4.analysis.h5'

hf = h5py.File(filename, 'r')

keys = hf.keys()
group2 = hf.get('tracks')
tracks = []
for k in range(len(group2)):
    tracks.append(group2[k])
    
tracks = np.array(tracks).squeeze().transpose(2,1,0)
print (tracks.shape)
(10000, 11, 2)
```

**Comment by talmo** [comment]
Hi @catubc,

No worries, let's figure this out :)

First, what do you mean by "output video"? Is this a rendered video exported from the GUI with tracking? (I don't see any tracking overlaid on the video at that link.)

Second, the code snippet looks fine, but it does seem like there's only 1 track? Are you supposed to have 3 like in the video?

Do you mind sharing the analysis.h5 file so I can have a look?

**Comment by catubc** [comment]
Thanks Talmo

I put all the data here:
- a video to predict on
- .h5 and .slp file for inference only
- .h5 and .slp file for same but with optical flow tracking

https://drive.google.com/drive/folders/1KPS8OQPXZ9miTFnAgiwYbxqP2igtZYGN?usp=sharing

Re the video I posted: this is the video in this folder with the values from the inference only output which appear as large white squares in the video, hovering mostly at the bottom of the screen. 

Re: # of tracks, I'm still not clear what sleap outputs. I've been working with DLC for a long time and I usually assemble and track my own animals.  I did see the optical flow file had 3800+ tracks (?) for this video, but wasn't sure what that meant.

Thanks so much,

**Comment by talmo** [comment]
I see -- yeah you're right that the predictions look totally random. Definitely something wonky going on here and I don't think it's the tracking. The problem seems to be the pose estimation, so I'm surprised that it looked fine in the GUI.

Were the models trained on this video?

If you'd like, I can dig into some more if you could share the model folders (`201208_111035.centered_instance.60` and `201208_110240.centroid.60`), the labels (`.slp`) or the training package (`.pkg.slp`) if you exported one.

**Comment by catubc** [comment]
Hi Talmo

1.  So, turns out that I made a mistake and tried to predict/infer features on a dataset from a different recording (night time etc.).  When I run the tracking on the same/similar video, it does work.  Sorry about this confusion (we have multiple cohorts). 

https://drive.google.com/file/d/1j2Bf0btoFHQnr4OCpOwWtdfVVzeOtWKd/view?usp=sharing

2.  This is decent results given just 60 frames that we trained on, but it's problematic for at least 2 I don't think are related to insufficient training. The first is that a track is split across 2 animals (we see these in DLC as well) and 2nd is there seem to be multiple detections of the same animal.  

https://drive.google.com/file/d/154WSlgXmUWzkMChoypgEwHU9FS-OoNml/view?usp=sharing

3.  In comparison, DLC inference step + our own graphical animal assembly approach gives us already this on similar videos. As you can see the tracks are relatively stable over time:

https://drive.google.com/file/d/11Tcizwr408f2UVGyp7cDQbpK2dpx_EAj/view?usp=sharing

I really like your tool and would like to know more. We have thousands of hours of social behaviours and are setting up to gather even more now.  (btw: I like that you guys save assembled + connected tracks;  submitted a CoSyNe abstract exactly on how to fix them automatically using CNNs. )

If you wish to chat sometime, please let me know and we can setup a zoom. 
catubc

**Comment by talmo** [comment]
Hi @catubc,

Yeah it looks like the model didn't quite learn to produce good PAFs so the grouping doesn't work so well, resulting in split instances and such. Usually this happens when the loss weight is imbalanced between confidence maps and PAFs (I think we might have it 5 to 1 in some profiles).

It might also just be a bug, so happy to dig into it further! I'll check it out with the data you put in the drive folder.

Regarding tracking fixing and chatting further: definitely interested! Drop me an email at `talmo@princeton.edu` and we can find a time to chat.

**Comment by catubc** [comment]
Thanks Talmo. I will message you shortly.

In the meantime, here's the dataset, I've uploaded the entire sleap directory here:

https://drive.google.com/file/d/17-yEo4iGxwY08vtppzObBp1SqiLVkRbz/view?usp=sharing

Also, do you recommend that I try to train on all the hand-labeled data I have. I currently only trained on 60 images, but I have around 1,500+.  I am not sure how long training would take, but if you think it's worth it to move us along, I can try doing it (merging .csv files somehow!).

**Comment by talmo** [comment]
I'm going to go ahead and close this issue since we've been discussing this offline.

If anyone finds this in a search, here's the bit that's relevant to the specific error:

> Hi @catubc,
> 
> Give it a go with the .h5 file generated by **File** -> **Export Analysis HDF5...** or by running `sleap-convert --format analysis "/home/cat/Downloads/sleap_video.mp4.slp"`.
> 
> This file doesn't contain any of the SLEAP metadata that might be harder to parse when reading from another program.
