### ISSUE TITLE
How to access the bees and mice dataset?

### ISSUE THREAD

**Issue by FariaOaishi** [murthylab/sleap#439]
Hello, Thank you for the materials! I had a question regarding the dataset.

When I visited the dataset github repository, I could only find out a video for flies (drosophila), is there any publicly available data sample for mice and bees as well?

**Comment by talmo** [comment]
Hi @FariaOaishi,

Sure thing. Here are the datasets we used for the preprint: https://osf.io/r3pdu

Let me know if you have any questions!

Cheers,

Talmo
