### ISSUE TITLE
Can't find "Show Trails" in the "View" menu

### ISSUE THREAD

**Issue by adorbens** [murthylab/sleap#442]
Happy new year and thank you so much for developing SLEAP! It really helps a lot especially in studying social behavior, the only problem so far is we're having trouble differentiating identities. I've tried following the instruction on the SLEAP website, it says turning on track trails would help a lot, but I can't seem to find the "Show Trails" command, I can see the "Trail Length" tho. In addition, "Next Track Spawn Frame" can't be selected either, as shown in the picture. 
Sorry about asking these basic questions, I'm not really good at coding and thus really grateful for y’all developing this wonderful tool!

![IMG_8712](https://user-images.githubusercontent.com/65748596/103496600-d8308580-4e79-11eb-9558-eed7d840aac8.PNG)
![IMG_8713](https://user-images.githubusercontent.com/65748596/103496607-dd8dd000-4e79-11eb-8cc7-afd3130de85e.PNG)

**Comment by talmo** [comment]
Hi @adorbens,

Happy new year! Glad you're liking SLEAP :)

Try this:

1. Go to **View** -> **Apply Distinct Colors To** -> **instances**
2. Go to **View** -> **Trail Length** -> Pick a number of frames **>0**

If you're not seeing the instances being colored individually, you might not have run inference with *tracking* enabled ([see this page](https://sleap.ai/tutorials/proofreading.html)).

Let me know if that works for you. Cheers!

Talmo
