### ISSUE TITLE
Importing DeepLabCut dataset with grayscale images results in videos with 3 channels

### ISSUE THREAD

**Issue by SamMinkowicz** [murthylab/sleap#463]
Hi, I have a DeepLabCut dataset with labeled grayscale images. However, when I import it into SLEAP they are imported with 3 channels. Is there a place to specify that these are grayscale?

Thanks!
Sam

**Comment by talmo** [comment]
Hi @SamMinkowicz,

Good question. The easiest thing you can do without changing the image format or reimporting the original videos is to force the images to be grayscale when training models:
![image](https://user-images.githubusercontent.com/3187454/105538974-0ea73680-5ca9-11eb-9b4d-d9ac0525cda1.png)

This will trigger RGB -> grayscale conversion when the images are being loaded for training or inference, even if they appear as RGB in the GUI.

Let me know if that works for you. Cheers!

Talmo

**Comment by SamMinkowicz** [comment]
Hi Talmo, thanks for the quick reply! That sounds straightforward I'll try that!

Sam
