### ISSUE TITLE
Predictions are all nan

### ISSUE THREAD

**Issue by SamMinkowicz** [murthylab/sleap#464]
Hi, I trained a model with: [initial_config.txt](https://github.com/murthylab/sleap/files/5907007/initial_config.txt). During training this warning happened almost every epoch (Error occurred when finalizing GeneratorDataset iterator: Unknown: KeyError: 115) you can see the full training output in this file [train_output.txt](https://github.com/murthylab/sleap/files/5907015/train_output.txt). 

I then ran the `sleap-track` and `sleap-convert` commands in v1.1.0a9. But the predictions are all nans when looking at the contents in the ".analysis.h5" file with code like in the "Analysis examples" colab notebook.

Any ideas on what I did wrong?

Thanks for your help!
Sam

**Comment by talmo** [comment]
Hi @SamMinkowicz,

Well this is a new one! Yeah there definitely seems to be something funky going on with the data loading during training. I'm surprised it worked at all...

A couple q's:

1. What SLEAP version are you on?
2. Which menu option did you select when you exported the training package?
3. Do you mind sharing the `padded.pkg.slp` on Google Drive or something? (Feel free to email it if you prefer to share it privately.)

Cheers!

Talmo

**Comment by SamMinkowicz** [comment]
Hi Talmo,

I trained with version 1.0.0 but did inference with version 1.1.0a9. I used the Export Training Package option. Just emailed it to you!

Thanks for your help!
Sam

**Comment by talmo** [comment]
Hi @SamMinkowicz,

Looking back at the email thread I think we're set with this issue right? Feel free to re-open if not!

For future reference: we improved the model by tweaking some augmentation settings to encourage robustness to contrast/illumination.
