### ISSUE TITLE
Can't open gui in stable SLEAP version after gui was opened in v1.1.0a10

### ISSUE THREAD

**Issue by SamMinkowicz** [murthylab/sleap#479]
**Steps to reproduce:** 
open the gui in  v1.1.0a10 and then try to open the gui in the stable version.
Raises: 
`yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:PySide2.QtCore.QByteArray'
  in "C:\Users\sam/.sleap/preferences.yaml", line 16, column 15`

I imagine this would occur for any version prior to v1.1.0a10 but haven't tested it.

Prevents the user from using multiple versions on one machine. But maybe this is a rare occurrence.

**Comment by talmo** [comment]
Hi @SamMinkowicz,

Yup, sorry about that! Dangers of alpha releases :(

For now you can fix this by deleting `C:\Users\sam/.sleap/preferences.yaml` when switching versions.

I'll tag this as a bug though so we have something permanent before the full release.

Cheers,

Talmo

**Comment by ariematsliah-princeton** [comment]
Hi @SamMinkowicz 
This issue should be fixed from [v1.1.0](https://github.com/murthylab/sleap/releases/tag/v1.1.0) onward.
Closing for now, please feel free to reopen if your issue is not resolved.
