### ISSUE TITLE
Assigning names to unspecified tracks

### ISSUE THREAD

**Issue by donw7** [murthylab/sleap#483]
Hello,
I was wondering if there's an easy way to correct all the "Track: [none]" instances to one particular name. Right now it appears that these instances can only be corrected one frame at a time, whereas tracks w/ names can be corrected and all the following frames will also be renamed. I also can't seem to find "Track: [none]" tracks in the exported hd5 dataset. Maybe I'm missing something? I'm having an issue where for certain stretches in two-mouse tracking, one mouse has a track name but the other does not. The predicted node locations are fine. I can certainly try re-running w/ other parameters but was wondering if there's an easier solution (esp. if it's simply in the exported dataset somewhere that I can't find).

If not, here are the parameters I ran with:

  --tracking.tracker flow \
  --tracking.target_instance_count 2 \
  --tracking.pre_cull_to_target 1 \
  --tracking.pre_cull_iou_threshold 0.8 \
  --tracking.track_window 30 \
  --tracking.kf_init_frame_count 10 \
  --tracking.kf_node_indices 1,2,3 \
  --tracking.post_connect_single_breaks 1 \

Thank you for your help!

**Comment by donw7** [comment]
Also, using topdown

**Comment by talmo** [comment]
Hi @donw7,

Very sorry about the delay! I've been swamped with a major deadline this week.

That's very weird. Every mouse should have a track assigned if tracking is enabled and the pose is detected.

Was this possibly from a previous run?

Also, what SLEAP version are you on?

Thanks!!

Talmo

**Comment by donw7** [comment]
No worries, thanks very much for your help!

This was on 1.0.10 on colab. I believe I had the same issue in the past in the GUI as well but it wasn't as significant. 

Not sure what you mean by 'previous run,' but there was about 20 videos batch processed in the same way on colab and 2 of them had this issue in a more significant way.

**Comment by talmo** [comment]
Hmm, this is the second time I've seen this in the last few days so I'm inclined to believe there's something funky going on with the tracking.

With regards to export: that's intentional. If we don't know which track to stick the pose into, we can't add it to the array. The problem is that you shouldn't be getting instances back without a track assigned in the first place.

Do you mind sharing your .slp file where this issue is most frequent? You can drop a link here or email it to `sleap@princeton.edu`. I'll try to get you a workaround while we track down this bug.

Cheers!

Talmo

**Comment by ntabris** [comment]
@talmo: If I recall correctly, the Kalman filter based tracker won't assign tracks to instances if two instances are both nearly equally good matches for the given track. Relevant comment: https://github.com/murthylab/sleap/blob/develop/sleap/nn/tracker/kalman.py#L476-L479

**Comment by talmo** [comment]
Thanks @ntabris!! That narrows it down so we can find a fix.

@donw7, I think I already suggested this over email, but do you still see this issue without the Kalman filter enabled?

**Comment by donw7** [comment]
There does not appear to be this issue when the kalman filter is disabled. Will send the slp files via email. Thanks very much!
