### ISSUE TITLE
Error in training hourglass: TypeError: __init__() missing 1 required positional argument: 'channel_ind'

### ISSUE THREAD

**Issue by SamMinkowicz** [murthylab/sleap#485]
Hi I am getting an error when trying to train a single animal centered instance model with an hourglass backbone. There is a warning that "Gradients do not exist for variables..." followed by a long list of variables and then it throws TypeError: __init__() missing 1 required positional argument: 'channel_ind'.

Here is the config file: [centered_instance.txt](https://github.com/murthylab/sleap/files/6023897/centered_instance.txt) and the output: [hourglass.txt](https://github.com/murthylab/sleap/files/6023886/hourglass.txt)

Thanks for your help!
Sam

**Comment by talmo** [comment]
Just a quick update: this is a bug we're aware of and will be working on. Thanks @SamMinkowicz!

**Comment by SamMinkowicz** [comment]
Sweet thanks!
