### ISSUE TITLE
Full video inference, skeleton lagging

### ISSUE THREAD

**Issue by calebvogt** [murthylab/sleap#489]
OS: Windows 10
Install: Anaconda
SLEAP version: stable v1.0.10

Hi! First, thanks for open-sourcing this software, I have really enjoyed using it so far. 

I am tracking ~150 videos of a single mouse in a two-choice style open field assay. Iteratively running the training on randomly generated frames does a great job of adding the skeleton over the mouse correctly. I have done this up multiple times on randomly generated frames and I get good results. 

The problem arises when running the inference over the entire video. Over the course of the 15 minute video (@30FPS), the skeleton drifts away from where the mouse is actually located. 

Early in the video: 
![image](https://user-images.githubusercontent.com/15038280/108907977-cd2fe100-75f0-11eb-95ba-023741371985.png)

Late in the Video:
![image](https://user-images.githubusercontent.com/15038280/108908035-dd47c080-75f0-11eb-87d7-1888288bff6d.png)

Mid video on a image I manually added the instance, after inference was run on the full video:
![image](https://user-images.githubusercontent.com/15038280/108908145-fa7c8f00-75f0-11eb-8637-366161f09a36.png)

At first I thought my issue was related to this issue: https://github.com/murthylab/sleap/issues/411

I reconverted all of my videos using the ffmpeg code you provided in the response to the above issue, however as you can see from the screenshots above, the issue persists. 

Thanks in advance for you assistance on this! Let me know what I can do differently. I have a vague feeling that it may have something to do with the video itself and the way ffmpeg is converting it...

**Comment by talmo** [comment]
Hi @calebvogt,

Thanks for the detailed issue report!

Yeah this sounds like a classic video seeking issue. So you're saying you've tried re-encoding them before running inference?

Try this:
```
ffmpeg -i "input.avi" -c:v libx264 -preset superfast -crf 21 -pix_fmt yuv420p "output.mp4"
```
Then track the new file:
```
sleap-track -m "path/to/model" -o "predictions.slp" "output.mp4"
```

If this is already what you did, do you mind sharing an example clip (and preferably the trained model you're trying to use) with `sleap@princeton.edu`?

Thanks!!

Talmo

**Comment by calebvogt** [comment]
Hi Talmo, 

Excellent, thank you for your response and ffmpeg code. Converting my videos with that line does appear to fix the problem. I had previously converted the videos using this ffmpeg line:

ffmpeg -i "input.avi" -c:v libx264 -preset superfast -pix_fmt yuv420p "output.avi"

Note that instead of converting my avi videos into mp4s, I originally kept them as avis and the problem remained. converting them to mp4's using:

ffmpeg -i "input.avi" -c:v libx264 -preset superfast -crf 21 -pix_fmt yuv420p "output.mp4"

solves the issue. thanks!

Unrelated: How does one apply inference on ALL videos in the project? I can only see the option to apply inference on the current selected video using the GUI. I often am tracking hundreds-thousands of videos at once, so going through them individually would be impractical. Can this be achieved using the GUI, or does this need to be done via the command line? I might have missed this in the tutorial.

**Comment by calebvogt** [comment]
Hi Talmo, 

Excellent, thank you for your response and ffmpeg code. Converting my videos with that line does appear to fix the problem. I had previously converted the videos using this ffmpeg line:

ffmpeg -i "input.avi" -c:v libx264 -preset superfast -pix_fmt yuv420p "output.avi"

Note that instead of converting my avi videos into mp4s, I originally kept them as avis and the problem remained. converting them to mp4's using:

ffmpeg -i "input.avi" -c:v libx264 -preset superfast -crf 21 -pix_fmt yuv420p "output.mp4"

solves the issue. thanks!

Unrelated: How does one apply inference on ALL videos on ALL frames in the project? I can only see the option to apply inference on all frames for the current selected video using the GUI.  Can this be achieved using the GUI, or does this need to be done via the command line? I might have missed this in the tutorial. Thanks in advance for you help. 

![image](https://user-images.githubusercontent.com/15038280/109313005-b8806280-7815-11eb-8b09-0c046860459d.png)
