### ISSUE TITLE
KeyError: 'oks_voc.mAP' while training single instance 

### ISSUE THREAD

**Issue by calebvogt** [murthylab/sleap#499]
OS: Windows 10
SLEAP: v.1.0.10, run locally on GPU. 

Hi,

I am receiving the following error when re-training a single instance network. My process was as follows: 
Import videos using the GUI > Generate sample suggestions > labelled ~20 frames > Run training for single animal on suggested frames (this ran perfectly with no errors, and generated instances on all suggested frames > labelled an additional 70 frames > Run training for single animal on suggested frames > and then I get the below error. 

![image](https://user-images.githubusercontent.com/15038280/109707295-fc51cf80-7b67-11eb-9ee2-6d4e0cfc5553.png)

I find this a little odd just because the training worked on the first frames I labelled. 

Here is a drive link to the .slp file, models and prediction folder: https://drive.google.com/drive/folders/1gn3GWycb49AHwUb6KH2KeHor87xDQzkj?usp=sharing

Thanks for the assistance!

**Comment by ariematsliah-princeton** [comment]
Hi @calebvogt 
Thanks for the detailed report. We'll check the issue and update this ticket with findings. In the meantime please consider upgrading to the latest release ([v1.1.0](https://github.com/murthylab/sleap/releases/tag/v1.1.0)) which includes many improvements and fixes.

Best

**Comment by calebvogt** [comment]
I'm not sure how I missed rolling up to v1.1. I'll close this in the meantime.
