### ISSUE TITLE
Failed to convert object of type <class....>

### ISSUE THREAD

**Issue by calebvogt** [murthylab/sleap#500]
Software versions:
SLEAP: 1.1.0
TensorFlow: 2.3.1
Numpy: 1.18.5
Python: 3.6.12
OS: Windows-10-10.0.18362-SP0

Issue: I keep running into the following error when I attempt to use the GUI to train a top down model with just a few labelled frames on a new project. The training initiates and typically runs to about 18/200 epochs (or less) before throwing the following error and halting the process. Closing the error window starts the centered instance model configuration, but then that also ends up throwing the same error after 10-20 epochs. 

![image](https://user-images.githubusercontent.com/15038280/109886707-84120980-7c4e-11eb-9eda-2bf85bd3fe34.png)

Let me know if I can provide any further information!

**Comment by ariematsliah-princeton** [comment]
Hi @calebvogt ,
We're looking into this - will update here once we identify the issue.
Thanks for reporting

**Comment by ariematsliah-princeton** [comment]
@calebvogt could you share the .slp file please?
And also, are you training on multiple videos with different sizes?

Thanks

**Comment by calebvogt** [comment]
I thought all of my videos were 1080p, but I just realized that there are several that are at a reduced resolution of 480p. I am going to separate these videos from my other videos and will attempt to retrain on the 1080p videos only to see if the issue resolves itself and will report back. Thanks for pointing this out!

**Comment by calebvogt** [comment]
Excellent, it appears that mixing different resolution videos in the training project folder was the source of this error. Thank you for your rapid response!!!

**Comment by ariematsliah-princeton** [comment]
Glad that you were able to unblock yourself @calebvogt 
We are working on fixing the issue with multi-size videos and it should be included in the upcoming release.

Cheers

**Comment by calebvogt** [comment]
hm, reopening this as I seem to have hit another (potentially related?) snag with the same project. 

All the videos in the training project are now 1080p mp4s, but some are shot at 30 fps and some are at 15. Would this potentially be the cause of this error (see screenshot)? 

![image](https://user-images.githubusercontent.com/15038280/110027874-8765cd80-7d00-11eb-85fa-13387aa7fcd6.png)

Here is a screenshot of folder where the validation.png file in question is located. The file is not opened in any other application. 

![image](https://user-images.githubusercontent.com/15038280/110028081-ceec5980-7d00-11eb-898f-e1c840c5acb6.png)

additionally, I've sent the slp file to the email address above for your reference. 

Thanks in advance for your help, and please let me know if I can provide further files/info

**Comment by talmo** [comment]
Hi @calebvogt,

We're working on that bug too, but for now you can basically ignore it. If you were expecting to get predictions back after training (e.g., on suggestions), you can just go to Predict -> Run Inference... and select the model you just trained.

Let me know if that works :)

Cheers,

Talmo

**Comment by ariematsliah-princeton** [comment]
Hi @calebvogt ,

Can you please try again after upgrading to latest version ([v1.1.1](https://github.com/murthylab/sleap/releases/tag/v1.1.1))?

Thank you

**Comment by calebvogt** [comment]
Thanks for circling back to me on this!

Ok, I rolled up to v1.1.1. I retrained my single animal network and attempted to predict on: entire video. The training runs and the model seems to update and save. Black vertical bars appear indicating that instances were predicted on all frames, but no yellow skeleton "prediction" instances are actually drawn on any of the frames. The following error is thrown repeatedly in the console: 

![image](https://user-images.githubusercontent.com/15038280/110394208-0b3df380-803a-11eb-86b6-2d6234ea5cd9.png)

For reference, I was running into this issue with v.1.1.0 as well. 

I will send my .slp file via email. Thanks for taking a look at this!

**Comment by calebvogt** [comment]
An additional screenshot showing the lack of a predicted instance. That said, the predicted instance score is only 0.25, so perhaps there is some thresholding that is happening that is preventing the predicted instance from being drawn? 

![image](https://user-images.githubusercontent.com/15038280/110394413-696ad680-803a-11eb-8b33-c7225ca3c9b5.png)

**Comment by ariematsliah-princeton** [comment]
Hi @calebvogt 
There are 2 separate issues here:
1. The model is not able to predict any instances in your video (we'll look into this and let you know if we need any input from you).
2. When 1. happens, SLEAP should behave better (and ideally notify the user with informative message instead of crashing). This is something we can address in the next release.

Thanks

**Comment by talmo** [comment]
Hi @calebvogt,

Bugs aside (especially after updating to [SLEAP v1.1.2](https://github.com/murthylab/sleap/releases/tag/v1.1.2)), are you still seeing this problem with the training totally failing and resulting in the empty sequence issue?

**Comment by calebvogt** [comment]
This issue appears to be resolved as of v1.1.3. Thank you!
