### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal....

### ISSUE THREAD

**Issue by calebvogt** [murthylab/sleap#510]
Software versions:
SLEAP: 1.1.1
TensorFlow: 2.3.1
Numpy: 1.18.5
Python: 3.6.12
OS: Windows-10-10.0.19041-SP0

Issue: I am getting this error when attempting to initialize a top-down multi-animal centroid training model (all settings kept at the default settings). It appears the centroid model never trains. 

![image](https://user-images.githubusercontent.com/15038280/110550974-aef2d680-8102-11eb-9497-d86549e5e5f0.png)

After closing the pop up, the Centered instance model starts to train, but no instances are predicted. 

I've sent the project file to the sleap email.

**Comment by talmo** [comment]
Hi @calebvogt,

Sorry for the delay! Just wanted to let you know that we can reproduce your issue and are working on a fix.

FYI, this has to do with the video frames being of a weird size -- SLEAP should be able to handle this adaptively, but for some reason it's not picking it up in this case.

If you can crop/resize your videos to have each dimension be 192, 256, 384, 512, etc., it should serve as a work around while we fix this.

Cheers,

Talmo

**Comment by calebvogt** [comment]
Hi Talmo, sorry for the delayed response. I have reviewed all of my videos that are in this project folder, and at least according to windows file explorer, all of the mp4 videos are exactly 1920x1080p. Do you suggest resizing them anyway using FFMPEG?  Thanks for the help.

**Comment by talmo** [comment]
Hi @calebvogt,

This issue should now be fixed in [SLEAP v1.1.2](https://github.com/murthylab/sleap/releases/tag/v1.1.2)!

Give it a spin with the new version and feel free to re-open if you're still seeing this problem.

Cheers!

Talmo

**Comment by talmo** [comment]
Quickie update: if you're running into issues when training a centroid model, switch to [SLEAP v1.1.3](https://github.com/murthylab/sleap/releases/tag/v1.1.3) -- otherwise, all fixes should still work.

**Comment by calebvogt** [comment]
Hi Talmo, apologies for the late response, but I can confirm that this (and other issues) are fixed in v1.1.3. Thank you!
