### ISSUE TITLE
Combining previous training labels with additional predicted and fixed labels post-model 

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#512]
Hi

1. We have a labeled dataset named abc.slp that comes from 20+ vids.  We have about 800 labeled frames pooled from all the videos.

2.  We trained a (top-down ID) model using the abc.slp file and next want to predict using the CLI frames from the original 20 vids and iterate through this training process. 

3.  Ideally, we would pick a small percentage of frames from the 20 videos, predict them, adjust the predictions and then pool them to the 800 labeled frames already.  What is the easiest way to do this? 

It's not clear how to do this from the CLI (i.e. combine the 800 human labeled with another 200-300 predicted and fixed frames).  Does the GUI allow us to load the models and predict specifically on some frames?  

[edit] I did see the wiki, but it wasn't completely clear which and how many frames are inferred ?

https://sleap.ai/tutorials/assisted-labeling.html

I will try it shortly, but if you have any clarifications based on our use-case, it would be much appreciated.

Thanks so much,
catubc

**Comment by catubc** [comment]
Ok, I think we're going to try following the wiki first, it seems possible to do the first part via CLI in the cloud, and then correct locally with the GUI.

**Comment by ariematsliah-princeton** [comment]
Thanks for using the Wikis :)
Please report if you get blocked
