### ISSUE TITLE
FileNotFoundError: Could not find training profile: baseline.topdown_confmaps.json

### ISSUE THREAD

**Issue by safas25** [murthylab/sleap#514]
I am running a multi-animal top-down training pipeline and have been successful in training the centroid model. When I run the command for training the centered instance model, I am receiving the following error:

2021-03-14 19:06:31.495821: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1 
Traceback (most recent call last): 
File "/usr/local/bin/sleap-train", line 8, in 
sys.exit(main()) 
File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 1531, in main 
raise FileNotFoundError(f"Could not find training profile: {job_filename}") 
FileNotFoundError: Could not find training profile: baseline.topdown_confmaps.json

![Screen Shot 2021-03-15 at 10 58 40 AM](https://user-images.githubusercontent.com/80673676/111121218-6cefe780-857d-11eb-9a48-540611e055e2.png)

Just for a little background, I am trying to train the system to locate the thorax of four flies and eventually calculate the distance between the thoraxes to translate to social interaction.

**Comment by ariematsliah-princeton** [comment]
Hi @safas25 
Thanks for reporting this issue. We'll check and get back to you if we need more information.
In the meantime can you provide the version of SLEAP you are using? Perhaps also try to do the same after fresh install of the [latest version ](https://github.com/murthylab/sleap/releases/tag/v1.1.1) ?

**Comment by safas25** [comment]
> Hi @safas25
> Thanks for reporting this issue. We'll check and get back to you if we need more information.
> In the meantime can you provide the version of SLEAP you are using? Perhaps also try to do the same after fresh install of the [latest version ](https://github.com/murthylab/sleap/releases/tag/v1.1.1) ?

Hey! Could you guide me how to check the version?

**Comment by safas25** [comment]
> If you have the labeling GUI open, it should show the version on the left/top corner (something like "Sleap v1.1.1")
> Or you can look at the terminal output when launching the GUI, it will print out something like this:
> 
> Software versions:
> SLEAP: 1.1.1
> TensorFlow: 2.3.1
> Numpy: 1.18.5
> Python: 3.6.12
> OS: Windows-10-10.0.19041-SP0

Neither of those appear :/

**Comment by ariematsliah-princeton** [comment]
Then you are probably on an older version.
Can you install the latest (see instructions [here](https://github.com/murthylab/sleap/releases/tag/v1.1.1)) and try again? If desired, you can install it in a new conda environment (in parallel to your existing version).

**Comment by safas25** [comment]
> Then you are probably on an older version.
> Can you install the latest (see instructions [here](https://github.com/murthylab/sleap/releases/tag/v1.1.1)) and try again? If desired, you can install it in a new conda environment (in parallel to your existing version).

Sure, will try and update. Thank you!

**Comment by safas25** [comment]
> Then you are probably on an older version.
> Can you install the latest (see instructions [here](https://github.com/murthylab/sleap/releases/tag/v1.1.1)) and try again? If desired, you can install it in a new conda environment (in parallel to your existing version).

Hi! I updated SLEAP and re-ran the entire procedure, still getting the same error. 

SLEAP version:
Software versions:
SLEAP: 1.1.1
TensorFlow: 2.3.1
Numpy: 1.18.5
Python: 3.6.13
OS: Darwin-19.3.0-x86_64-i386-64bit

Error:
2021-03-16 07:54:10.531290: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/usr/local/bin/sleap-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 1531, in main
    raise FileNotFoundError(f"Could not find training profile: {job_filename}")
FileNotFoundError: Could not find training profile: baseline.topdown_confmaps.json

**Comment by ariematsliah-princeton** [comment]
Do you mind sharing your .slp file to help us debug this issue? You can email it to sleap@princeton.edu
Thanks

**Comment by safas25** [comment]
> Do you mind sharing your .slp file to help us debug this issue? You can email it to [sleap@princeton.edu](mailto:sleap@princeton.edu)
> Thanks

Sure, sent! Thank you.

**Comment by ariematsliah-princeton** [comment]
Hi @safas25 
Are you running training from the GUI or commandline? Looks like it is pointing to a built-in config file that was renamed. Can you explain how exactly you run training?

Thanks

**Comment by safas25** [comment]
> Hi @safas25
> Are you running training from the GUI or commandline? Looks like it is pointing to a built-in config file that was renamed. Can you explain how exactly you run training?
> 
> Thanks

Hi!
I run it on the GUI. Basically, after selecting the nodes and instances, I label 20 frames randomly generated by the software, and export the training package. I then run training with the following settings: multi-animal top-down training/inference pipeline type, a sigma of 10 for centroids, thorax as the anchor point, and a sigma of 5 for nodes. I don't change anything in the "Centroid Model Configuration" and "Centered Instance Model Configuration" tabs. Then I just save configuration files, which generates these files: inference-script.sh, train-script.sh, centered_instance.json, centroid.json. I then upload required files on Google Drive and run on Google Colaboratory.

**Comment by safas25** [comment]
> Hi @safas25
> Are you running training from the GUI or commandline? Looks like it is pointing to a built-in config file that was renamed. Can you explain how exactly you run training?
> 
> Thanks

Hi! Any ideas on how to resolve the issue?

**Comment by safas25** [comment]
> Hi @safas25
> Are you running training from the GUI or commandline? Looks like it is pointing to a built-in config file that was renamed. Can you explain how exactly you run training?
> 
> Thanks

Hi! Any updates on the issue?

**Comment by talmo** [comment]
Hi @safas25,

Yes! We're in the process of updating the notebooks and pushing a couple fixes which should be done today or tomorrow. If you want to give it a spin early, try out training from this notebook:

https://colab.research.google.com/github/murthylab/sleap/blob/arie/update-notebooks/docs/notebooks/Training_and_inference_using_Google_Drive.ipynb

We'll update this thread when the update is ready but feel free to let us know if you have any questions!

**Comment by talmo** [comment]
Hi @safas25,

You can now follow along in this notebook: https://sleap.ai/notebooks/Training_and_inference_using_Google_Drive.html

And feel free to let us know if you run into any issues! Hopefully the Colab-based workflow is a bit clearer now.

Closing this but feel free to re-open if you're running into problems. Cheers!

Talmo

**Comment by talmo** [comment]
Quickie update: if you're running into issues when training a centroid model, switch to [SLEAP v1.1.3](https://github.com/murthylab/sleap/releases/tag/v1.1.3) -- otherwise, all fixes should still work.

Also, other notebook examples can be found here: https://sleap.ai/notebooks

**Comment by safas25** [comment]
> Quickie update: if you're running into issues when training a centroid model, switch to [SLEAP v1.1.3](https://github.com/murthylab/sleap/releases/tag/v1.1.3) -- otherwise, all fixes should still work.
> 
> Also, other notebook examples can be found here: https://sleap.ai/notebooks

Hi! Thank you very much! Will try it out and update.
