### ISSUE TITLE
Predictions are shifted from actual limb positions

### ISSUE THREAD

**Issue by SamMinkowicz** [murthylab/sleap#516]
Hi I have a dataset with images of slightly different sizes. To train a model with them (before #501), I padded them all to the max image size and was able to successfully train a model. However, the predictions are all shifted from the actual limbs when performing inference on a video with dimensions smaller than the max image size (see an example below). It seems like the padding added for inference is being added to the top and left instead of the bottom and right. 

I performed inference with version 1.1.1

Thanks for your help!
Sam

![here](https://user-images.githubusercontent.com/42850123/111354499-61bbbb00-8654-11eb-8cf5-6ed061b32a3b.png)

**Comment by ariematsliah-princeton** [comment]
Hi @SamMinkowicz 
Can you share your project file (.slp) to look into this issue? You can email it to sleap@princeton.edu

Thanks

**Comment by talmo** [comment]
Hi @SamMinkowicz,

We had a chance to have a look at your project file and I had a couple of questions:

1. What video(s) are you seeing those shifted predictions on?
2. Do you see the same issue both on the "image videos" that you imported from DLC as well as on the AVI files you added to the project?

Thanks!

**Comment by SamMinkowicz** [comment]
Hi Talmo,

I just sent an email to sleap@princeton.edu with a link to the video and the output from running inference on that video. The video might not actually be in the sleap project since I performed training and inference remotely.

I don't see this issue on the imported "image videos." 

Thanks for all your help!
Sam

**Comment by talmo** [comment]
Hi @SamMinkowicz,

Sorry for the delay -- this was a tricky one to track down!

The problem was that the video was of a different size than the images used model -- and importantly, of a different aspect ratio. SLEAP pads the images to account for this, but we neglected to adjust the coordinates for the scaling factor afterwards.

This is fixed now and will be included in the next release (v1.1.2), coming out in the next day or so. I'll re-open this just so I remember to ping update this thread when the release is out.

Talmo

**Comment by SamMinkowicz** [comment]
Thank you @talmo! I'll look out for the release.

Sam

**Comment by talmo** [comment]
Hi @SamMinkowicz,

This issue should now be fixed in [SLEAP v1.1.2](https://github.com/murthylab/sleap/releases/tag/v1.1.2)! Give it a spin and feel free to re-open if you're still seeing this bug.

Cheers!

Talmo

**Comment by talmo** [comment]
Quickie update: if you're running into issues when training a centroid model, switch to [SLEAP v1.1.3](https://github.com/murthylab/sleap/releases/tag/v1.1.3) -- otherwise, all fixes should still work.

**Comment by SamMinkowicz** [comment]
Thanks for the update!
