### ISSUE TITLE
Colored, predicted instances shift when selected

### ISSUE THREAD

**Issue by olinesn** [murthylab/sleap#518]
Hi, I'm writing to report a GUI bug. I'm using SLEAP v1.1.1, but the bug has been present in previous versions.

Step 1: **Predict > Run Inference > Predict On: Current Frame > Run** gives 3 predicted instances:
Instance 1: Blue
Instance 2: Orange
Instance 3: Yellow
![image](https://user-images.githubusercontent.com/69451171/111985395-f30eaf80-8ae2-11eb-85d8-e979a267f9f2.png)

Step 2: Double click on a point from the blue instance, Instance 1. All instance numbers/colors shift, and this instance now become Instance 3 (Yellow).

![image](https://user-images.githubusercontent.com/69451171/111985425-f99d2700-8ae2-11eb-96bb-555ad3589f4a.png)

Is there a way to keep the instance numbers constant when selecting the predicted instances?
Thanks!

**Comment by talmo** [comment]
Hi @olinesn,

Fixes this in v1.1.4 -- you can update with the instructions here: https://github.com/murthylab/sleap/releases/tag/v1.1.4

Cheers,

Talmo
