### ISSUE TITLE
Deleting frames in GUI not working

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#530]
Hello

We have a large labeled dataset (about 900 frames) that we're trying to separate into two files (so we can train 2 NNs separately).  We think that splitting the labeled frames into 2 different files (one for night time, another for day time videos) will work better, but didn't realize it at the beginning of the project.  So we're now trying to split the main .slp (which has 900 frames as mentioned) into 2 of about 450 frames each.

We tried deleting some of the labeled frames using the right menu, but it seems that frames still persist in the videos (see attached pic of frame 3553). This occurs even if we save and reload the deleted file. What does seem to work is right clicking on every single frame (image panel on the left) and deleting the labels manually - but this is very slow.

Are we using the menu incorrectly?  What would be the fastest way to delete hundreds of labeled frames for our task.

Thanks so much,
catubc
![sleap_delete](https://user-images.githubusercontent.com/4267452/112600892-0a66d900-8e12-11eb-8354-04d16d63705a.png)

**Comment by talmo** [comment]
Hey @catubc, do you see any errors in the console?

**Comment by catubc** [comment]
I will check with student and post soon.
Thanks

**Comment by catubc** [comment]
Hi. 
There were no errors in the console.

But there's an option in the labels dropdown menu to "Custom instance delete" for an entire video. This seems to work much faster than single instance deletion and it works.

Thanks for the help.
