### ISSUE TITLE
Merge two projects with same videos

### ISSUE THREAD

**Issue by Xiaoyu-Tong** [murthylab/sleap#532]
Hi,

I was trying to merge a project to another one. These projects have same videos but different sets of frames are labeled. So basically I want the merged project to have all labels (union set of those in two projects). However, either "use new, discard base" or "use base, discard new" seem to keep only labeled frames from one project. How can I merge two projects which have same videos while keeping all the labeled frames? Thank you!

(By the way, I believe to re-open an issue is a privilege of developers. Users cannot do that)

Xiaoyu

**Comment by talmo** [comment]
> I was trying to merge a project to another one. These projects have same videos but different sets of frames are labeled. So basically I want the merged project to have all labels (union set of those in two projects). However, either "use new, discard base" or "use base, discard new" seem to keep only labeled frames from one project. How can I merge two projects which have same videos while keeping all the labeled frames? Thank you!

Hmm, for frames that don't overlap they should be both added. Did you get any error in the console?

Alternatively, would you like to share the two .slp files? (No need for the videos/images/training package)

> (By the way, I believe to re-open an issue is a privilege of developers. Users cannot do that)

Whoops, you're right! I think you can only re-open it if you were the one that opened. You _can_ reply to it though, so feel free to do that and I'll re-open.

**Comment by Xiaoyu-Tong** [comment]
Hi @talmo ,

I did not get any error in the console, but in merged project the all labels from one parent project are missing. I guess at least some info is preserved as I can see light-blue bars below, those are frames with discarded labels. Those frames which still have labels are normal-blue bars. Probably it is worth-mentioning that for those labeled frames, they have predictions in the other project. Is it possible that this causes the issue? And sure, I can share the .slp files if that helps. Thank you!

**Comment by ariematsliah-princeton** [comment]
Can you try deleting all predictions before merging and see if it works?

**Comment by ariematsliah-princeton** [comment]
Hi @Xiaoyu-Tong 
We're closing this now but feel free to reopen if this is still an issue
