### ISSUE TITLE
Error in open DeepLabCut csv file: TypeError: can_read_file() missing 1 required positional argument: 'file'

### ISSUE THREAD

**Issue by Shelly9018** [murthylab/sleap#542]
Hi, I am attempting to use sleap.io.format.deeplabcut.LabelsDeepLabCutCsvAdaptor to transfer my csv data that labeled by DeepLabCut. My code is the following:
file_path = "***.csv"
file_handle = filehandle.FileHandle(file_path)
deeplabcut.LabelsDeepLabCutCsvAdaptor.can_read_file(file_handle.file)
And I got a TypeError:
deeplabcut.LabelsDeepLabCutCsvAdaptor.can_read_file(file_handle.file)
TypeError: can_read_file() missing 1 required positional argument: 'file'

I'm using v1.1.3 for training.

Thanks for your help!
Shelly

**Comment by ariematsliah-princeton** [comment]
Hi @Shelly9018 
Note that '[can_read_file](https://github.com/murthylab/sleap/blob/971ce0b9fb364adccb1396c1139e6996ad1231f3/sleap/io/format/deeplabcut.py#L53)' is not static, so you can't call it from LabelsDeepLabCutCsvAdaptor directly.

**Comment by ariematsliah-princeton** [comment]
Closing this for now, please Google instance methods vs static methods and if something still isn't working as expected please reach out.

**Comment by talmo** [comment]
Hi @Shelly9018,

It looks like you're trying to import multiple CSVs?

Here's how you can import a single file DLC CSV file:

```py
labels = sleap.Labels.load_file("dataset1.csv", as_format="deeplabcut")
```

If you need to add more than one experiment that are in the same folder, you can use this API:
```py
labels = sleap.Labels.load_deeplabcut_folder("/path/to/dataset_folder")
```

This will search subfolders for *.csv files, similar to what you're trying to do based on your code snippet.

Give that a go and let us know if you're still having issues.

Talmo

**Comment by ariematsliah-princeton** [comment]
Thanks @talmo for the detailed response 👍

**Comment by talmo** [comment]
Closing this for now. Feel free to comment or open a new issue if you're still having problems @Shelly9018.

Cheers,

Talmo
