### ISSUE TITLE
Select which GPU to use

### ISSUE THREAD

**Issue by mfkeles** [murthylab/sleap#546]
Fantastic work, and excellent documentation. Thoroughly enjoyed reading the guide. 

I am switching from DLC and training on a local machine. I couldn't find an option to specify which GPU to use. My local machine has two when I start the training the one I want to use (1080 Ti) is not utilized. 

Thank you, 

-M

**Comment by talmo** [comment]
Hi @mfkeles,

Glad you like it!

You can currently specify the GPU for [inference](https://sleap.ai/guides/cli.html#inference-and-tracking), but not training -- definitely something we can add though.

If you're running from the CLI, an easy way to do this should be to set an environment variable before calling `sleap-train`:
```
export CUDA_VISIBLE_DEVICES="1"
```

If you're training from the GUI, I *think* it should also work if you set that environment variable before calling `sleap-label`.

Let me know if that works for you while we work on adding GPU specification to the training CLI.

Cheers,

Talmo

**Comment by mfkeles** [comment]
yep did the trick! thank you!

**Comment by talmo** [comment]
Great! And I added GPU specification to the training CLI in #547, so it'll be available in our next release.

Feel free to reply here or open a new issue if you're running into problems.

Cheers!
