### ISSUE TITLE
question: tracking visually distinguishable instances

### ISSUE THREAD

**Issue by pwang724** [murthylab/sleap#557]
Hi, really enjoying playing with the software thus far. What would be the recommended approach for tracking two socially interacting individuals that are visually distinguishable? In my specific case, it would be mice of different coat colors (white vs black). As I peruse the guides, I did not find a tracking option tailored for this scenario. Should I train two models? One for the black coat and another for the white coat? Should I use sleap or leap?

**Comment by talmo** [comment]
Hi @pwang724,

Terrific question!

If you have particularly distinguishable individuals, there's a couple of options available in SLEAP:

1. You can use the `flow` tracker method which will leverage visual information to compute displacements across frames and more reliably associate instances over time. This doesn't explicitly model the appearances, but it _does_ take advantage of that information.

2. You can use one of our ID-based models which explicitly train models to recognize visually distinguishable classes of animals. This works terrifically if you can tell them apart reliably during the labeling. We're still polishing off some sharp edges on the user interface for using these models, but if you're interested in trying it out, shoot us an email and we'll provide instructions on how to install and use it --> `sleap@princeton.edu` 

I'll go ahead and close this issue but please feel free to comment again or shoot us an email if you want to follow up.

Cheers,

Talmo
