### ISSUE TITLE
GUI: Text color change for non-visible nodes

### ISSUE THREAD

**Issue by olinesn** [murthylab/sleap#560]
Hi,

I'm writing to ask if the text for non-visible nodes could be a different color than for visible nodes of the same skeleton. At the moment, there's just a change from Normal to Bold text style, and so it's tough to spot quickly if there are any nodes that haven't been labelled as visible. Maybe non visible could be gray, and visible the teal that it currently is?

Thanks!
Stefan

**Comment by talmo** [comment]
Hi @olinesn,

Added this enhancement in v1.1.4 -- you can update with the instructions here: https://github.com/murthylab/sleap/releases/tag/v1.1.4

Cheers,

Talmo

**Comment by olinesn** [comment]
Nice, thanks!
