### ISSUE TITLE
.h5 analysis files: Tracks data frame has XY values, but no probability column

### ISSUE THREAD

**Issue by calebvogt** [murthylab/sleap#561]
Hi all,

Thanks again for all your work on this software! I was wondering why the .h5 files (which I obtain by using the sleap-convert --format analysis argument on all of my .slp files) lack the probability column under the nested tracks dataframe. One of my goals is to use the track cleaning script and sample analysis notebook you provide on the h5 files, and then port them into a software like SIMBA for additional ROI/ethogram analyses. It seems however that SIMBA needs the probability column for XY locations, and I can imagine that it might be useful to have that probability information for a custom post-tracking analysis approach as well. 

An alternative approach might be to directly run interpolation on the .slp files, but building the post-tracking analysis around the h5 files seems like the way to go. Thanks in advance for any clarification that can be provided here!

**Comment by talmo** [comment]
Hi @calebvogt,

Added this enhancement in v1.1.4 -- you can update with the instructions here: https://github.com/murthylab/sleap/releases/tag/v1.1.4

Cheers,

Talmo
