### ISSUE TITLE
Modification/Bug for #560

### ISSUE THREAD

**Issue by olinesn** [murthylab/sleap#565]
![SLEAP_gray](https://user-images.githubusercontent.com/69451171/123474779-7d761c00-d5c8-11eb-81c5-3aba74b02596.png)

Thanks for adjusting the text color for nodes that are not included in training, this has actually helped me catch a few mistakes in labelled frames. I think there's an interaction now though that has created a bug. Selecting "Color predicted instances" makes the instances become invisible rather than colored, while leaving it unselected and then editing the skeletons makes them colored. This doesn't interrupt the workflow too much so it's not urgent.

I'm coming to regret asking that the text color be gray for what's mostly grayscale videos, maybe this could be a high contrast color like yellow in the future?

Best,
Stefan

**Comment by talmo** [comment]
This is now fixed in SLEAP v1.1.5: https://github.com/murthylab/sleap/releases/tag/v1.1.5

Closing but feel free to reply if this is still an issue.
