### ISSUE TITLE
Video frame loading error

### ISSUE THREAD

**Issue by escobarg** [murthylab/sleap#566]
Hi there! 
I have run several iterations of the training and wanted to run predictions the entire video i had been training it with. After selecting that option i keep receiveng the following error indicating that it can not access frame 21164. There are 21166 frames. The run seems to work well up until this point. I have tried to run the program several times but I cant quite figure out why it is unable to load the frame. 

Thank you!
<img width="1179" alt="Screen Shot 2021-06-30 at 1 09 31 AM" src="https://user-images.githubusercontent.com/85850249/123926076-645ec980-d940-11eb-9656-75a2d0541921.png">

**Comment by talmo** [comment]
Hi @escobarg,

This sounds like a seekability issue with the file format. Check out the solution at https://github.com/murthylab/sleap/issues/564#issuecomment-866117837 and let me know if you're still running into this error after reencoding.

Cheers,

Talmo

**Comment by escobarg** [comment]
<img width="810" alt="Screen Shot 2021-07-07 at 1 35 55 AM" src="https://user-images.githubusercontent.com/85850249/124727560-b022ed00-dec3-11eb-9625-9007986bfa15.png">
Hi there! I was able to install ffmpeg but i keep getting this error upon conversion. Any tips? Thank you!

**Comment by talmo** [comment]
Hi @escobarg,

What was the exact command you used when you got that error?

**Comment by escobarg** [comment]
I used the one you had suggested: 
fmpeg -i "input.avi" -c:v libx264 -preset superfast -crf 21 -pix_fmt yuv420p "output.mp4" 

and then I tried this after reading a thread from a similar user problem [Linked here](https://stackoverflow.com/questions/49686244/ffmpeg-too-many-packets-buffered-for-output-stream-01) . the screen shot is from this line of code:
fmpeg -i "input.avi" -c:v libx264 -preset superfast -crf 21 -pix_fmt yuv420p "output.mp4" -max_muxing_queue_size 1024

**Comment by talmo** [comment]
Hmmmm, ok so for the second command, you definitely want to have that added flag before the "output.mp4", so try something like this:

```
ffmpeg -y -i "input.avi" -c:v libx264 -preset superfast -crf 21 -pix_fmt yuv420p -max_muxing_queue_size 1024 -an "output.mp4"
```
(This also drops what appears to be the audio track with the `-an` flag above.)

If that still doesn't work, do you mind dropping the AVI file on Google Drive or something and sending it to `sleap@princeton.edu`?

**Comment by escobarg** [comment]
Hi there! It worked thank you so much! I think it was mainly the audio that was messing up the file conversion.
