### ISSUE TITLE
Invisible nodes predicted with --peak_threshold 0

### ISSUE THREAD

**Issue by SBergeler** [murthylab/sleap#576]
Hi,

I used the option --peak_threshold 0 (or negative values) to get predictions for all nodes. However, I still get invisible nodes in the predictions (tested in SLEAP version 1.1.3 and 1.1.4). Why is this the case?

Thank you!

**Comment by talmo** [comment]
Hey @SBergeler,

This was a bug and fixed in #571. It'll be fixed in SLEAP v1.1.5 which will be ready soon. I'll leave this issue open and let you know when it's released.

Cheers,

Talmo

**Comment by SBergeler** [comment]
Great, thank you, Talmo!

**Comment by talmo** [comment]
This is now fixed in SLEAP v1.1.5: https://github.com/murthylab/sleap/releases/tag/v1.1.5

Closing but feel free to reply if this is still an issue.
