### ISSUE TITLE
Using jupyter notebooks or Atom to track

### ISSUE THREAD

**Issue by EvynDickinson** [murthylab/sleap#583]
I'm trying to track videos on my local machine using jupyter notebooks in my sleap conda environment (or atom) to iterate through multiple videos. I can't seem to get the correct syntax for calling sleap-track. 
I'm able to run a similar code block in a google colab and it loops through my videos without problem but when I transfer over to a local machine I get a series of unexplained 'syntax errors'.

Code used to loop through videos:
files = [tt for tt in os.listdir('.') if os.path.isfile(tt) and (tt.endswith('.avi'))]
for tt in files:
  sleap-track (tt) \
    --tracking.tracker simple \
    -m centered_instance_model \
    -m centroid_model

Example error:
File "<ipython-input-16-fc5d49a6cd55>", line 5
    --tracking.tracker simple \
                                        ^
   SyntaxError: invalid syntax

**Comment by talmo** [comment]
Hi @EvynDickinson,

If you're running in Ipython (which Colab does), its [magics](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-system) let you can use `!sleap-track`, for example:

```py
import os

centroid_model = "models/my_centroid_model"
centered_instance_model = "models/my_centered_instance_model"

videos = [x for x in os.listdir('.') if os.path.isfile(x) and (x.endswith('.avi'))]
for video in videos:
    !sleap-track --tracking.tracker simple -m "{centroid_model}" -m "{centered_instance_model}" "{video}"
```
In this syntax, local variables (like `centroid_model` or `video`) are replaced in system calls in lines that start with a `!`.

Let us know if that works for you!

Talmo

**Comment by talmo** [comment]
Closing this but please feel free to reply here or open a new issue if you still need any help!
