### ISSUE TITLE
Translation between predictions and animal locations in GUI

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#584]
Hello 
So we have this weird issue that the videos/frame predictions have a weird DC offset in both x and y.  

We are using an NN trained on different videos to predict on the attached images. Both the training images and prediction images have the same size though (900 x 700 pixels).  Is Sleap assuming the images are 1280 x 1024 when making the videos - but not when doing inference (inference seems ok for many body parts)?

Thanks so much,

![example1](https://user-images.githubusercontent.com/4267452/133246860-b1406c8f-a2c2-44c1-b213-eda000260460.png)
![example2](https://user-images.githubusercontent.com/4267452/133246867-21d7f122-f891-4a2a-b218-daae9819e254.png)

**Comment by talmo** [comment]
Hey @catubc,

Is this still on the ID model version?

It looks like #516 which we fixed in v1.1.3.

If so, bear with me while we port the ID models to the new version! Sorry :(

**Comment by catubc** [comment]
Hey @talmo , 
Yes, we are certainly using the ID model.
Ok, let us know re fix; we will need this soonish to continue training the rest of the cohorts.
Is there a hack in the mean time?  
Thanks so much!

**Comment by talmo** [comment]
Closing this issue thread, but we'll follow up in #596 as soon as we can.
