### ISSUE TITLE
question about points that aren't in frame

### ISSUE THREAD

**Issue by vcorbit** [murthylab/sleap#600]
Hi, I'm not sure if this is the best place for this question so please redirect me if there is a better platform!

I am trying to analyze some videos where the mouse moves out of frame sometimes. I need to find these periods of time. In the SLEAP predictions, we have trained enough that we are pretty reliably getting no predicted labels when the mouse isn't in frame. However, the GUI says it's finding all 20 of my points (see image). Additionally, when I look at my h5 output file, I did not see the NaNs I expected to see when there are no labels. In the past when I have had occlusions in tracking, I typically get a NaN at that frame for that point. However that doesn't seem to be happening here. Can someone lend some insight or thoughts on how to use the SLEAP output to do what I need to do (identify periods when the mouse disappears)?

Thanks!
![image](https://user-images.githubusercontent.com/55154685/139309096-b0c5adce-3b8f-445c-9217-fccfed09523d.png)

**Comment by talmo** [comment]
Hi @vcorbit,

That's odd... What kind of numbers do you get in the h5 file when you export it?

Do you mind sharing the SLP file and the frame number where this happens?

Thanks!

Talmo

**Comment by vcorbit** [comment]
Hi Talmo,

Yes, definitely happy to share some examples! 

I will email you an example set of mp4/slp/h5 files where this happens. Unfortunately it also seems I'm having some issues with the GUI - it's not updating the frame number in the bottom display bar when I click through to the frames where no points were found. If I click to another frame where the mouse is present, it then updates the frame number. See these screenshots:
![image](https://user-images.githubusercontent.com/55154685/140068007-31bd9f9b-9ffa-4314-b2e9-81a156029a9d.png)
![image](https://user-images.githubusercontent.com/55154685/140068065-887a1e9d-f822-4a75-a947-6293d8a4b980.png)

Therefore, I can't tell you exactly which frames when the mouse isn't in the frame, but it appears to be a bunch of frames between 8000 and 9000. I tried to attach my files here but it wouldn't let me so I will email you!! 

Thanks!

**Comment by vcorbit** [comment]
Hi,

I did some test runs with a previous version of my SLEAP model, and in that case I see the nans when the animal is out of the frame. This leads me to believe there is some issue with how we are labeling frames when the animal isn't there, because we recently added a bunch of new frames with the animal not there, for training purpose... 

What is the proper way to tell SLEAP that the points aren't there? It seems there are kind of 3 modes for a point during labeling - red (predicted but not user-altered), teal (user-labeled), and gray (user-removed?). We had been labeling points that aren't visible by using the gray version of these labels, but is that not the correct way to do this?

Thanks for any advice!

**Comment by talmo** [comment]
Hi @vcorbit,

Interesting -- I'm not sure why this was different in a previous version of SLEAP but that's helpful to know.

You're marking points as not visible correctly -- they should be grey.

GUI issue: Yup, this is a GUI bug but shouldn't affect anything.

As far as analysis goes, however, what's the problem exactly? I think what you want to have is all NaNs for frames in which the animal isn't in the frame, correct? (As far as I can tell, this is what you're getting in your `analysis.h5` file.)

**Comment by vcorbit** [comment]
Wow, sorry, I don't know how I didn't see those, must've been looking at the wrong timestamps or something. You're right, the NaNs seem to be there! I apologize for the confusion. Thanks so much Talmo!!
