### ISSUE TITLE
3 GUI feature requests

### ISSUE THREAD

**Issue by olinesn** [murthylab/sleap#613]
Hello, writing to request three features for labelling:

1. Force "greyed out" predicted nodes to be inside the frame. Otherwise, I have to move the whole skeleton to be able to grab the ones outside the frame, and then move the skeleton roughly back to where it started.

2. When importing a large number of videos, a button for "Import all as greyscale" would be great.

3. A button for GO TO most recently labelled frame would be a luxury. Sometimes I'm labelling a frame and I accidentally press a combination of "Next Labelled" and "Next Suggested" and lose my place, and can't get back to a half-labelled frame.

Thanks!

**Comment by roomrys** [comment]
These features are now available in sleap 1.2.0 and above.
