### ISSUE TITLE
"propagate track labels" is not documented

### ISSUE THREAD

**Issue by smidm** [murthylab/sleap#626]
The menu option Tracks -> Propagate Track Labels is not documented.

**Comment by talmo** [comment]
Thanks @smidm! We'll add this to the docs. In the meantime, what this option does is to toggle whether SLEAP should adjust all subsequent instances when assigning a track. This is helpful when doing proofreading to fix swaps. When it's disabled, it lets you assign instances to tracks without affecting other frames.

**Comment by roomrys** [comment]
Time to update the docs, rediscovered in #714. Closing this issue and continuing thread on #714
