### ISSUE TITLE
how to add predicted instances to training dataset quickly?

### ISSUE THREAD

**Issue by escobarg** [murthylab/sleap#631]
i understand that there is a button that can be pressed for this but let's say that we have several predictions made on an entire video how can we include most/all of them to the training dataset in an efficient manner? Thank you for your help!

**Comment by talmo** [comment]
Hi @escobarg,

Sorry for the delay! Here's a quick example that should do what you're looking for (you can run this in a script or a notebook):

```py
import sleap

# Load predictions
labels_pr = sleap.load_file("predictions.slp")

# Create user instances from predictions
lfs = []
for lf in labels_pr:
    lfs.append(sleap.LabeledFrame(
        video=lf.video,
        frame_idx=lf.frame_idx,
        instances=[sleap.Instance.from_numpy(inst.numpy(), skeleton=inst.skeleton) for inst in lf]
    ))
labels_gt = sleap.Labels(lfs)

# Save
labels_gt.save("labels_from_predictions.slp")
```

From there you can import and merge the generated `labels_from_predictions.slp`.

Let me know if that works for you or if there's anything you'd like to add to it like score or track filtering or something to fit your needs.

Cheers,

Talmo

**Comment by talmo** [comment]
Hi @escobarg, I'll close this for now but please feel free to reply or reach out if the solution above doesn't work for you.
