### ISSUE TITLE
Install issue - wheel dependency problems

### ISSUE THREAD

**Issue by jstnkttll331** [murthylab/sleap#658]
Trying a fresh install of sleap, install goes smoothly, Downloads wheel-0.37.1 as a dependency, but when I try to launch sleap-label I get  the error "DistributionNotFound: The "wheel>=0.26' distribution was not found and is required by tensorflow.

If i type 'wheel version' I get 'wheel 0.37.1'. Not sure why.

Here's the full stack, including the installation

(base) C:\Windows\system32>conda create -y -n sleap -c defaults -c sleap sleap p
ython=3.6 -y
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry
 with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: C:\Users\Justin\anaconda3\envs\sleap

  added / updated specs:
    - python=3.6
    - sleap

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2021.5.30          |   py36haa95532_0         140 KB
    cudatoolkit-10.1.243       |       h74a9793_0       300.3 MB
    cudnn-7.6.5                |       cuda10.1_0       179.1 MB
    geos-3.8.0                 |       h33f27b4_0         905 KB
    intel-openmp-2022.0.0      |    haa95532_3663         2.4 MB
    jpeg-9d                    |       h2bbff1b_0         283 KB
    libtiff-4.2.0              |       hd0e1b90_0         786 KB
    lz4-c-1.9.3                |       h2bbff1b_1         132 KB
    mkl-service-2.3.0          |   py36h196d8e1_0          45 KB
    mkl_fft-1.3.0              |   py36h46781fe_0         131 KB
    mkl_random-1.1.1           |   py36h47e9c7a_0         235 KB
    numpy-1.19.2               |   py36hadc3359_0          22 KB
    numpy-base-1.19.2          |   py36ha3acd2a_0         3.8 MB
    olefile-0.46               |           py36_0          49 KB
    pillow-8.3.1               |   py36h4fa10fc_0         676 KB
    pip-21.2.2                 |   py36haa95532_0         1.9 MB
    pyside2-5.14.1             |   py36h6538335_0       120.5 MB  sleap
    python-3.6.13              |       h3758d61_0        14.6 MB
    setuptools-58.0.4          |   py36haa95532_0         776 KB
    shapely-1.7.1              |   py36h06580b3_0         369 KB
    six-1.16.0                 |     pyhd3eb1b0_1          18 KB
    sleap-1.1.5                |           py36_0       142.6 MB  sleap
    sqlite-3.37.2              |       h2bbff1b_0         799 KB
    tensorflow-2.3.1           |           py36_0       331.9 MB  sleap
    tk-8.6.11                  |       h2bbff1b_0         3.3 MB
    vc-14.2                    |       h21ff451_1           8 KB
    vs2015_runtime-14.27.29016 |       h5e58377_2        1007 KB
    wheel-0.37.1               |     pyhd3eb1b0_0          33 KB
    wincertstore-0.2           |   py36h7fe50ca_0          14 KB
    zlib-1.2.11                |       h8cc25b3_4         112 KB
    zstd-1.4.9                 |       h19a0ad4_0         478 KB
    ------------------------------------------------------------
                                           Total:        1.08 GB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  certifi            pkgs/main/win-64::certifi-2021.5.30-py36haa95532_0
  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.1.243-h74a9793_0
  cudnn              pkgs/main/win-64::cudnn-7.6.5-cuda10.1_0
  freetype           pkgs/main/win-64::freetype-2.10.4-hd328e21_0
  geos               pkgs/main/win-64::geos-3.8.0-h33f27b4_0
  intel-openmp       pkgs/main/win-64::intel-openmp-2022.0.0-haa95532_3663
  jpeg               pkgs/main/win-64::jpeg-9d-h2bbff1b_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            pkgs/main/win-64::libtiff-4.2.0-hd0e1b90_0
  lz4-c              pkgs/main/win-64::lz4-c-1.9.3-h2bbff1b_1
  mkl                pkgs/main/win-64::mkl-2020.2-256
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py36h196d8e1_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.0-py36h46781fe_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.1-py36h47e9c7a_0
  numpy              pkgs/main/win-64::numpy-1.19.2-py36hadc3359_0
  numpy-base         pkgs/main/win-64::numpy-base-1.19.2-py36ha3acd2a_0
  olefile            pkgs/main/win-64::olefile-0.46-py36_0
  pillow             pkgs/main/win-64::pillow-8.3.1-py36h4fa10fc_0
  pip                pkgs/main/win-64::pip-21.2.2-py36haa95532_0
  pyside2            sleap/win-64::pyside2-5.14.1-py36h6538335_0
  python             pkgs/main/win-64::python-3.6.13-h3758d61_0
  setuptools         pkgs/main/win-64::setuptools-58.0.4-py36haa95532_0
  shapely            pkgs/main/win-64::shapely-1.7.1-py36h06580b3_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  sleap              sleap/win-64::sleap-1.1.5-py36_0
  sqlite             pkgs/main/win-64::sqlite-3.37.2-h2bbff1b_0
  tensorflow         sleap/win-64::tensorflow-2.3.1-py36_0
  tk                 pkgs/main/win-64::tk-8.6.11-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py36h7fe50ca_0
  xz                 pkgs/main/win-64::xz-5.2.5-h62dcd97_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h8cc25b3_4
  zstd               pkgs/main/win-64::zstd-1.4.9-h19a0ad4_0

Downloading and Extracting Packages
wheel-0.37.1         | 33 KB     | #################################### | 100%
wincertstore-0.2     | 14 KB     | #################################### | 100%
mkl-service-2.3.0    | 45 KB     | #################################### | 100%
mkl_fft-1.3.0        | 131 KB    | #################################### | 100%
geos-3.8.0           | 905 KB    | #################################### | 100%
numpy-1.19.2         | 22 KB     | #################################### | 100%
zlib-1.2.11          | 112 KB    | #################################### | 100%
certifi-2021.5.30    | 140 KB    | #################################### | 100%
six-1.16.0           | 18 KB     | #################################### | 100%
sleap-1.1.5          | 142.6 MB  | #################################### | 100%
intel-openmp-2022.0. | 2.4 MB    | #################################### | 100%
sqlite-3.37.2        | 799 KB    | #################################### | 100%
pillow-8.3.1         | 676 KB    | #################################### | 100%
python-3.6.13        | 14.6 MB   | #################################### | 100%
libtiff-4.2.0        | 786 KB    | #################################### | 100%
setuptools-58.0.4    | 776 KB    | #################################### | 100%
pyside2-5.14.1       | 120.5 MB  | #################################### | 100%
numpy-base-1.19.2    | 3.8 MB    | #################################### | 100%
cudatoolkit-10.1.243 | 300.3 MB  | #################################### | 100%
lz4-c-1.9.3          | 132 KB    | #################################### | 100%
vc-14.2              | 8 KB      | #################################### | 100%
pip-21.2.2           | 1.9 MB    | #################################### | 100%
zstd-1.4.9           | 478 KB    | #################################### | 100%
tensorflow-2.3.1     | 331.9 MB  | #################################### | 100%
mkl_random-1.1.1     | 235 KB    | #################################### | 100%
jpeg-9d              | 283 KB    | #################################### | 100%
tk-8.6.11            | 3.3 MB    | #################################### | 100%
cudnn-7.6.5          | 179.1 MB  | #################################### | 100%
olefile-0.46         | 49 KB     | #################################### | 100%
shapely-1.7.1        | 369 KB    | #################################### | 100%
vs2015_runtime-14.27 | 1007 KB   | #################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate sleap
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) C:\Windows\system32>
(base) C:\Windows\system32>
(base) C:\Windows\system32>conda activate sleap

(sleap) C:\Windows\system32>sleap-label
Traceback (most recent call last):
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 568, in _build_master
    ws.require(__requires__)
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.2 (c:\users\justin\anaconda
3\envs\sleap\lib\site-packages), Requirement.parse('numpy<1.19.0,>=1.18.1'), {'s
leap'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Justin\anaconda3\envs\sleap\Scripts\sleap-label-script.py", lin
e 33, in <module>
    sys.exit(load_entry_point('sleap==1.1.5', 'console_scripts', 'sleap-label')(
))
  File "C:\Users\Justin\anaconda3\envs\sleap\Scripts\sleap-label-script.py", lin
e 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\importlib_metadat
a\__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\importlib\__init__.py", line 12
6, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sleap\__init__.py
", line 9, in <module>
    from sleap.io.dataset import Labels, load_file
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sleap\io\dataset.
py", line 61, in <module>
    from sklearn.model_selection import train_test_split
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sklearn\__init__.
py", line 82, in <module>
    from .base import clone
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sklearn\base.py",
 line 17, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sklearn\utils\__i
nit__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sklearn\utils\cla
ss_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sklearn\utils\val
idation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\sklearn\utils\fix
es.py", line 28, in <module>
    from pkg_resources import parse_version  # type: ignore
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 3242, in <module>
    @_call_aside
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Users\Justin\anaconda3\envs\sleap\lib\site-packages\pkg_resources\__i
nit__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel>=0.26' distribution was not found
 and is required by tensorflow

(sleap) C:\Windows\system32>wheel
usage: wheel [-h] {unpack,pack,convert,version,help} ...

positional arguments:
  {unpack,pack,convert,version,help}
                        commands
    unpack              Unpack wheel
    pack                Repack wheel
    convert             Convert egg or wininst to wheel
    version             Print version and exit
    help                Show this help

optional arguments:
  -h, --help            show this help message and exit

(sleap) C:\Windows\system32>wheel version
wheel 0.37.1

(sleap) C:\Windows\system32>

**Comment by Rodchi** [comment]
I'm getting same error on ubuntu 20.4.3LTS 
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel>=0.26' distribution was not found and is required by tensorflow

**Comment by Rodchi** [comment]
Hello! I just found the answer under conda or miniconda enviroment you must run the following commands. @jstnkttll331 
          conda create -y -n sleap_v1.1.5 -c sleap sleap=1.1.5
          conda activate sleap_v1.1.5
          pip install tensorflow==2.3.1

This creates a new env and install correct version of tf sleap needs . #614 just save me

**Comment by talmo** [comment]
Thanks for linking to the fix @Rodchi. This will get fixed in the upcoming v1.2.0 release.

In the meantime, you can follow the workaround in #614 or install the latest pre-release from https://github.com/murthylab/sleap/releases

Closing for now but let me know if these don't work for you @jstnkttll331.

**Comment by jstnkttll331** [comment]
Appreciate the help, to everyone! This project is amazing.
