### ISSUE TITLE
Issues with CUDA runtime....

### ISSUE THREAD

**Issue by jstnkttll331** [murthylab/sleap#662]
Still trying to get this reinstall up, and I appreciate all the help so far. When I try to run an inference on a video in the GUI using an existing trained model, I get the following error:

tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. S
tatus: CUDA driver version is insufficient for CUDA runtime version
  output: E:/Ant Data/Automator Scripts and Data/Library/test\predictions\0000-1
.avi.220307_150905.predictions.slp
  no_empty_frames: True
  verbosity: json
  video.dataset: None
  video.input_format: channels_last
  cpu: False
  first_gpu: False
  last_gpu: False
  gpu: 0
Process return code: 1

From conda list, I can see that I have cudatoolkit 10.1.143 and cudnn 7.6.5, as well as tensorflow 2.3.1.

Any quick guesses? I am running windows 7 and recently updated my cuda drivers using the windows application at https://developer.nvidia.com/cuda-downloads.

Thanks again,
Justin

**Comment by talmo** [comment]
Hi Justin,

If I had to guess I'd imagine that it's related to being on Windows 7, but I can't be sure.

If you use the conda-based installation method, you actually shouldn't need to install CUDA at all, which should make the version troubleshooting a bit easier.

Try it out with the latest pre-release and let me know if it works for you: https://github.com/murthylab/sleap/releases/tag/v1.2.0a6

Cheers,

Talmo
