### ISSUE TITLE
Hotkey for hiding skeletons

### ISSUE THREAD

**Issue by olinesn** [murthylab/sleap#665]
Hello,

Sometimes it's hard to see precisely where to place a node when the node itself obscures a target, and the target moves when flipping back and forth between frames. Maybe we could get a hotkey to hold/toggle for showing skeletons?

Thanks,
Stefan

**Comment by roomrys** [comment]
We added a hotkey (and menu item) to toggle the visibility of instances. This feature will be available in the next release. 

Thanks,
Liezl
