### ISSUE TITLE
GPU_0_bfc

### ISSUE THREAD

**Issue by jurieltoribio** [murthylab/sleap#671]
![image](https://user-images.githubusercontent.com/22687386/158010055-a8d5cf9b-a654-429f-b20b-f94f90213aa4.png)

![image](https://user-images.githubusercontent.com/22687386/158010749-0edadc2c-f030-4786-9863-3d8752848696.png)

Good day, How do you fix this error? i cant seem to use my gpu on training.

**Comment by talmo** [comment]
Hi @jurieltoribio,

That warning is actually just indicating that you might be a bit low on GPU memory. It just means you could have better performance with a smaller model or larger GPU, but regardless it still means your GPU is being used for training :)

Cheers,

Talmo
