### ISSUE TITLE
Following Message on 3050ti

### ISSUE THREAD

**Issue by Rodchi** [murthylab/sleap#677]
Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.
WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0218s vs `on_train_batch_end` time: 0.3121s)

Ubuntu 20.04.04LTS

Got prev message on training a single model animal

**Comment by talmo** [comment]
Hi @Rodchi,

This is just a warning and can be safely ignored.

It's just indicating that you might be a bit low on GPU memory. It just means you could have better performance with a smaller model or larger GPU.

Cheers,

Talmo
