### ISSUE TITLE
Duplicate keyboard shortcuts in 'Go' menu

### ISSUE THREAD

**Issue by ShivanshDave** [murthylab/sleap#686]
Same default shortcut set for navigating across labeled frames and videoes:
![image](https://user-images.githubusercontent.com/20853067/159343434-37eb664c-c03e-42c4-a0ae-c7f8d6d643f4.png)

I changed it from "Help > keyboard Shortcuts", but it would be great to have the default shortcuts changed. 
(Suggestion: kindly consider "Alt+Shift+Right/Left" for Videos -- they aren't assigned for anything else)

**Comment by talmo** [comment]
Thanks @ShivanshDave! We'll have a look at conflicting defaults.

**Comment by roomrys** [comment]
This bug fix will be implemented in the next release.
