### ISSUE TITLE
Issue training on colab

### ISSUE THREAD

**Issue by TheMalaland** [murthylab/sleap#689]
Hello, i've been working with sleap locally using my nvidia card so far, but since my skeleton went  more complex just as the dataset i wanted to use colab but when it stops training the model doesn't make any predictions neither on instances or videos, but i've ran this config locally and worked just fin. It does creates the predicted frames but no skeleton showed when download the model.5 or model.slp. this also happends when run inference on collab. There seems not to be a training issue since it shows train and val loss reduction on training epoch

I'm using the training config on predic/run training/export training job package config. i'm using sleap newest version v1.2.1 and a single_instance model

**Comment by talmo** [comment]
Hi @TheMalaland,

Are you seeing any errors appear in the Colab output when you try to run inference?

If you can save the Colab noterbook to your own Google Drive and share a link to it, that works too!

Thanks!

Talmo

**Comment by TheMalaland** [comment]
Thak you for your fast answer!
No, i don't see any inference error, it just appear to run fine but doesn't get to label anything

here's the link https://tinyurl.com/themalaland 

i thought it was something about the drive folders or so, i put everything on the same folder on colab and locally but same result

tksm!

**Comment by talmo** [comment]
Hi @TheMalaland, just FYI: I sent you a request to access the link above since I don't have permission to see it.

**Comment by TheMalaland** [comment]
I just gave you access, but i find out the problem was on the folder directions, i had to use the following command

!sleap-track /content/drive/MyDrive/sleap/Train02/videos/output8.mp4 \
  --frames 0,-308 \
  -m /content/drive/MyDrive/sleap/Train02/models/Dog_train_01.single_instance/training_config.json \
  --tracking.tracker flow \
  --tracking.pre_cull_to_target 0 \
  --tracking.pre_cull_iou_threshold 0.8 \
  --tracking.similarity instance \
  --tracking.match greedy \
  --tracking.track_window 5 \
  --tracking.post_connect_single_breaks 0 \
  -o /content/drive/MyDrive/sleap/Train02/predictions/output8_1.mp4.predictions.slp \
  --verbosity json \
  --no-empty-frames
   
it seems idk why when pass with short path the function can't take the models.

Is there a way to contine a model training after colab time limit finished?

**Comment by talmo** [comment]
Hi @TheMalaland,

Sorry for the delay! We've now added a notebook that should help with resuming model training in a new session: https://sleap.ai/notebooks/Interactive_and_resumable_training.html

Feel free to reply here or create a new thread if you're still having issues.

Cheers,

Talmo
