### ISSUE TITLE
Unable to run SLEAP GUI within Ubuntu WSL 2

### ISSUE THREAD

**Issue by SreeniEadara** [murthylab/sleap#708]
WSL 2 running Ubuntu on Windows 11. Using NVIDIA CUDA and have confirmed that CUDA is working.

I am encountering the following error when trying to launch sleap-label and also at epoch 1/200 in sleap-train:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

I have tried reinstalling the application by removing the Conda environment and reinstalling as the error message suggests. I also attempted updating WSL within Powershell and this did not affect the result.

Any and all help/feedback is appreciated. Thanks!!

P.S. is there a method to force sleap-train to run headless?

**Comment by SreeniEadara** [comment]
I was able to launch SLEAP GUI successfully. This appears to have been caused by bad symlinks for NVIDIA CUDA.

I followed the instructions in this post on microsoft/WSL issues to resolve it:
https://github.com/microsoft/WSL/issues/5663#issuecomment-1068499676

I will attempt training and mess around with the GUI a little more to see if it was fully resolved.

**Comment by roomrys** [comment]
Hi @SreeniEadara,

Thank you for posting the problem and following up with the solution! Glad that you found a fix that works. We will look into the symlink for NVIDIA CUDA and see if there is anything that can be done on our end to make the process a bit smoother. Keep us updated.

Thanks,
Liezl

**Comment by SreeniEadara** [comment]
Thanks for the response! I'm able to train and use the GUI successfully now with that fix. Closing the issue.
