### ISSUE TITLE
`--only-suggested-frames` exports predictions for all frames?

### ISSUE THREAD

**Issue by dataframing** [murthylab/sleap#712]
Hi there,

First of all, thank you for building and releasing `sleap`! It's been incredible so far.

I'm getting into the human-in-the-loop workflow of labeling on my local (M1 MacBook Air) laptop, exporting project and training job files to a Google Drive directory, running training + inference on Colab, then starting over with labeling using the model's suggestions for which frames to label. For the most part that works, but I'm not sure if I'm calling `sleap-track` correctly. For reference, I'm calling the command similar to the first inference command in the [Colab notebook](https://sleap.ai/notebooks/Training_and_inference_using_Google_Drive.html#predicting-instances-in-suggested-frames):

```bash
# Run inference just for suggested labeling frames.
!sleap-track {input_video_file} \
    -m {latest_centroid_model_dir} \
    -m {latest_centered_instance_model_dir} \
    --only-suggested-frames \
    --output {suggested_frames_inference_output_file} \
    --verbosity=rich \
    {latest_slp_training_job}
```

(In Colab, braces within inline shell commands are replaced with the string representation of that Python variable. Here, all variables are of type `pathlib.Path` and point to the various inputs and output file.) 

This command works and will run inference on the `input_video_file` MP4, but despite passing the `--only-suggested-frames` argument, it's instead running inference on the entire video _and saving the full video's predictions to the output `.slp` file_. I can understand if the algorithm is two-pass – i.e., the first pass is inference on the full video and the second pass is retrieving the top _k_ candidate frames for labeling (via some active learning sampling strategy, confidence sampling, or random sampling) – but it seems like the output `sleap` file at `suggested_frames_inference_output_file` contains predictions for all frames in `input_video_file`.

This isn't a deal-breaker, but it does make the merge phase difficult because the human labeler now has tens of thousands of suggested frames to label. I guess my questions are:

- Have I missed a simple way to specifically request (say) the top 20 suggested frames according to some sampling strategy?
- If not, is there a way to merge a full video's predictions and "order" the frames in ascending order of model confidence? That way we're still running inference over the entire input video, but at least the GUI can help you decide which (say) 20 frames are most important for labeling first?

Please let me know if I'm thinking about this incorrectly, or what I can do to help clarify my situation. Thank you!

**Comment by roomrys** [comment]
Hi @dataframing,

Glad you are enjoying SLEAP!

It seems you are providing multiple positional arguments for [`sleap-train`](https://sleap.ai/guides/cli.html#sleap-track) when only one is needed, namely [`data_path`](https://sleap.ai/guides/cli.html#:~:text=data_path%5D%0A%0Apositional%20arguments%3A-,data_path,-Path%20to%20data). In your code you specify two items to be used for `data_path`, first the video `input_video_file` and then at the very end you specify the `latest_slp_training_job`. The `sleap-track` command only takes in the first positional argument it sees and uses that as the `data_path`. Since you provide the video first, that is what SLEAP will use. However, the video alone does not have any information on which labels are suggested - the SLEAP Project file has this info.

Try removing the video from the command as below:
```
# Run inference just for suggested labeling frames.
!sleap-track {latest_slp_training_job} \
    -m {latest_centroid_model_dir} \
    -m {latest_centered_instance_model_dir} \
    --only-suggested-frames \
    --output {suggested_frames_inference_output_file} \
    --verbosity=rich 
```
Don't worry, the SLEAP Project file will know which video to use.

Let me know if the hypothesis was correct and if not we will find another fix!

Thanks,
Liezl

**Comment by dataframing** [comment]
Hi @roomrys! Thank you for replying so quickly. I didn't realize that I had been passing two positional arguments — thank you! I think I may now be running into a separate issue during inference with `--only-suggested-frames` that doesn't reproduce when I run the same `sleap-track` command without that flag:

```python
# First, delete the inference output file if it already exists.
suggested_frames_inference_output_file: Path = latest_slp_training_job_dir / "only-suggested-frames-inference.slp"
if suggested_frames_inference_output_file.is_file():
    suggested_frames_inference_output_file.unlink()
assert not suggested_frames_inference_output_file.is_file()

# Run inference just for suggested labeling frames.
!sleap-track {latest_slp_training_job} \
    -m {latest_centroid_model_dir} \
    -m {latest_centered_instance_model_dir} \
    --only-suggested-frames \
    --output {suggested_frames_inference_output_file} \
    --verbosity=rich
```
```pytb
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
Started inference at: 2022-04-26 08:03:41.287393
Args:
{
│   'data_path': '/content/drive/MyDrive/sleap-2/mouse-demo-jan/labels.v000.slp.training_job/labels.v000.pkg.slp',
│   'models': [
│   │   '/content/drive/MyDrive/sleap-2/mouse-demo-jan/models/220425_231629.centroid',
│   │   '/content/drive/MyDrive/sleap-2/mouse-demo-jan/models/220425_231629.centered_instance'
│   ],
│   'frames': '',
│   'only_labeled_frames': False,
│   'only_suggested_frames': True,
│   'output': '/content/drive/MyDrive/sleap-2/mouse-demo-jan/labels.v000.slp.training_job/only-suggested-frames-inference.slp',
│   'no_empty_frames': False,
│   'verbosity': 'rich',
│   'video.dataset': None,
│   'video.input_format': 'channels_last',
│   'cpu': False,
│   'first_gpu': False,
│   'last_gpu': False,
│   'gpu': 0,
│   'max_edge_length_ratio': 0.25,
│   'dist_penalty_weight': 1.0,
│   'batch_size': 4,
│   'open_in_gui': False,
│   'peak_threshold': 0.2,
│   'tracking.tracker': None,
│   'tracking.target_instance_count': None,
│   'tracking.pre_cull_to_target': None,
│   'tracking.pre_cull_iou_threshold': None,
│   'tracking.post_connect_single_breaks': None,
│   'tracking.clean_instance_count': None,
│   'tracking.clean_iou_threshold': None,
│   'tracking.similarity': None,
│   'tracking.match': None,
│   'tracking.track_window': None,
│   'tracking.min_new_track_points': None,
│   'tracking.min_match_points': None,
│   'tracking.img_scale': None,
│   'tracking.of_window_size': None,
│   'tracking.of_max_levels': None,
│   'tracking.kf_node_indices': None,
│   'tracking.kf_init_frame_count': None
}

Versions:
SLEAP: 1.2.2
TensorFlow: 2.8.0
Numpy: 1.21.5
Python: 3.7.13
OS: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic

System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
Available: True
        Initalized: False
     Memory growth: True

Predicting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ETA: -:--:-- ?
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 836, in __next__
    return self._next_internal()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 822, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2923, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 345, in _predict_generator
    for ex in self.pipeline.make_dataset():
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/data/pipelines.py", line 287, in make_dataset
    ds = transformer.transform_dataset(ds)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/data/normalization.py", line 342, in transform_dataset
    test_ex = next(iter(ds_input))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 838, in __next__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 4295, in main
    labels_pr = predictor.predict(provider)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 436, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 2126, in _make_labeled_frames_from_generator
    for ex in generator:
RuntimeError: generator raised StopIteration
```

Could this be related to the flag somehow?

**Comment by roomrys** [comment]
Hi @dataframing,

Happy to help!

The `--only-suggested-frames` argument gathers a list of indices in your video which are both a suggested frame AND unlabeled. Inference will then be run on this list of **unlabeled** suggested frames. By any chance, have you labeled all the suggested frames in your project? If so, we have an empty dataset to predict on. 

To fix this, add more labeling suggestions in your project (and leave them unlabeled) to predict on. Let me know if this works.

Thanks,
Liezl

**Comment by dataframing** [comment]
I must have totally misunderstood what that flag did. @roomrys if I'm looking to have a newly-trained model _suggest_ the top 20 frames for human labeling, is that possible via `sleap-track`? I know you can ask for a random sample of 20 frames from the GUI, but I suppose I'm looking for model-guided frame suggestions.

**Comment by roomrys** [comment]
Hi @dataframing, 

`sleap-track` will predict on the frames you specify, but will not suggest new frames for labeling. However, when you re-open `sleap-label` with the new project (which includes the predictions), there will be a score associated with each predicted frame as seen in the image below; the higher the score, the more confident SLEAP is that it is correct.

![image](https://user-images.githubusercontent.com/38435167/165582433-11664e6c-c724-4eea-b410-f60c874645fb.png)
**Im: Labeling Suggestions window in SLEAP GUI. The Mean Score represents how confident SLEAP is that the prediction is correct. To sort suggested frames by Mean Score, click on the Mean Score column header.**

We recommend labeling a few predictions within each confidence level - unfortunately, there is no current functionality for suggesting the top X number of frames to be labeled, but it is a great idea!

Hope this helps clarify things,
Liezl

**Comment by dataframing** [comment]
Ah, I see. I think I'm getting stuck on this idea of prediction-assisted labeling. So if I wanted a day-to-day workflow to cycle between training/inference in Colab and local GUI-based labeling, does this sound correct?

1. From the GUI, start a new `sleap` project, add a skeleton, and label (say) 10 frames.
2. From the GUI, request 20 random frames that will be used later for inference.
3. From the GUI, export the project `labels.v000.slp` and training job zip file `labels.v000.slp.training_job` to Google Drive.
5. In Colab, train the top-down centroid and centered-instance models on the 10 labeled frames.
6. In Colab, run inference (`!sleap-track ... --only-suggested-frames ...`) on just the unlabeled suggested frames from step [2]. This generates a file like `labels.v000.slp.training_job/only-suggested-frames-inference.slp`.
7. From the GUI, import that `labels.v000.slp.training_job/only-suggested-frames-inference.slp` file into your existing project, then view/edit/accept the predictions such that they become labels.
8. Restart at step [2], but now with 30 labeled frames and request another 20 unlabeled suggested frames. Rinse and repeat until we're happy with the model performance.

Aside from that, I'm now hitting an issue where if I open the `only-suggested-frames-inference.slp` project file I _do_ see the predictions for the 20 suggested frames from step [2] but none of the original labels, whereas if I instead open the originally-exported `labels.v000.slp` and try to merge the suggested frame inference file, I do see the original labels but none of the suggested frame inferences. I _feel_ like I'm doing something wrong – maybe I'm not supposed to "accumulate" predictions into the originally-exported project? – but I can't figure it out.

I realize this has diverged from the original issue, so please let me know if you'd prefer that I create a new issue here. Thank you for all of your help @roomrys! I really appreciate your patience as I learn about `sleap` 😅

**Comment by roomrys** [comment]
Hi @dataframing,

It sounds like you have a good grasp of what the process will look like. 

**Generating labeling suggestions**
I would like to note that you do NOT need to correct all the predictions, just the ones you want to - SLEAP only uses user-labeled instances in training. That being said, it is very important to either completely label a frame or not label it at all - do not leave any frames half-labeled. Also following from the above statement, we can produce ample Labeling Suggestions from the get-go and do not need to correct all of them. If you happen to run out of Labeling Suggestions before you are happy with the results, then I would add more.

**`.slp` returned from Colab**
The SLEAP Project File (`.slp` file) returned from Colab does not need to be imported into the existing project as it is the latest version of your project. Just go ahead and open this file in SLEAP.

I assume you have likely already read over the tutorial since you mention "prediction-assisted labeling", but I am just linking the [tutorial](https://sleap.ai/tutorials/tutorial.html) here for reference.

Lets start a new issue if you have more questions on the SLEAP process/another topic. We can link it here if it somewhat continues our discussion.

We appreciate you learning about SLEAP!
Liezl

**Comment by roomrys** [comment]
Closing the issue because it seems to be resolved.
