### ISSUE TITLE
unable to install sleap, using windows 11 home, and python 3.10.2, tried both methods

### ISSUE THREAD

**Issue by AmitaiOvadia** [murthylab/sleap#719]
I used the line "conda create -y -n sleap -c sleap -c nvidia -c conda-forge sleap=1.2.2" as instructed, and it was successfully set.

and then tried "pip install  pip install sleap==1.2.2"
the result:
ERROR: Could not find a version that satisfies the requirement PySide2<=5.14.1,>=5.13.2 (from sleap) (from versions: 5.15.2.1)
ERROR: No matching distribution found for PySide2<=5.14.1,>=5.13.2

Afterwards, I tried clone and set environment method: 
cloning was successful, 
but the line:  " conda env create -f environment.yml -n sleap"
resulted in:
SpecNotFound: Invalid name, try the format: user/package

Any help will be very much appreciated.
Amitai

**Comment by talmo** [comment]
Hi @AmitaiOvadia,

After doing `conda create -y -n sleap -c sleap -c nvidia -c conda-forge sleap=1.2.2` you can just activate the environment (`conda activate sleap`) and run it (`sleap-label`) -- no need to go on with the pip install or other methods.

Let me know if that works for you!

Talmo

**Comment by roomrys** [comment]
Hi @AmitaiOvadia,

Just to clarify, we only need to run one of the installation methods. It seems you tried to install using all three methods: [conda package](https://sleap.ai/installation.html#conda-package), [conda from source](https://sleap.ai/installation.html#conda-from-source), and [pip package](https://sleap.ai/installation.html#pip-package) even through the conda from source installation was successful. Please correct me if I misunderstood. 

If the [conda package installation method](https://sleap.ai/installation.html#conda-package) worked, then you should be good to go and able to use SLEAP. It may be useful to check that the sleap environment exists using the command `conda env list` to list all the existing conda environments first. You should see `sleap` listed as one of the conda environments as seen in the screenshot below:
![image](https://user-images.githubusercontent.com/38435167/166501163-95523b90-8602-46be-b345-d49d5733e556.png)


You can [test your installation](https://sleap.ai/installation.html#testing-that-things-are-working) of sleap by first activating the sleap conda environment via `conda activate sleap` and then running the command to open the gui `sleap-label` after the sleap environment has been activated.

Let me know if this helped, and if not please ask - happy to help!

Thanks,
Liezl

**Comment by AmitaiOvadia** [comment]
Hi @talmo , @roomrys ,
 
Thank you for your quick reply!
 
After successfully installing sleap with terminal command: "conda create -y -n sleap -c sleap -c nvidia -c conda-forge sleap=1.2.2"

I indeed tried:  "conda activate sleap" (which resulted in no reaction)
and then "sleap-label" 
which resulted in the following error:

"sleap-label : The term 'sleap-label' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again."

Have i done some of the steps wrong? or should I modify the command or the path somehow?

Thanks
Amitai

**Comment by talmo** [comment]
Hi @AmitaiOvadia,

Try running this in the **Anaconda Prompt** or the regular **Command Prompt** -- I think PowerShell might have some issues with conda if that happens to be what you're using.

Talmo

**Comment by AmitaiOvadia** [comment]
Hi @talmo,
It worked using the  Anaconda Prompt!
Thank you!

**Comment by talmo** [comment]
Terrific! Let us know if you run into any other issues.

Cheers,

Talmo
